### ISSUE TITLE
Connection failed issue while login

### ISSUE THREAD

**Issue by sagarpatil678** [mgp25/Chat-API-NET#1]
Hi,
I'm able to geneate request code and password. but when i'm trying to login with it, it is giving below error - "A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 184.173.147.60:443"

Error comes from below line-
this.socket.Connect("e" + random.Next(1, 17) + ".whatsapp.net", this.whatsPort);
(WhatsNetwork.cs file Line:72)

Can you please help me with it?
Do I need to make any changes in user agent value? (WhatsApp/2.12.68 S40Version/14.26 Device/Nokia302)

Phone number i'm using for API is using inserted in Nexus 4. Is it the reason for this?

**Comment by mgp25** [comment]
Invalid, this is working

**Comment by hpatel4u** [comment]
Agreed with @mgp25 its working fine.

@sagarpatil678 as per my knowledge there is nothing to do with the device you are using. Agent code should be the same as updated by mgp25.

**Comment by sagarpatil678** [comment]
Sorted. It was problem with my internet connection. I tried with different connection and it's working fine :)
Thanks for your reply
