### ISSUE TITLE
BinTreeNodeReader->readListSize: Invalid token 86 and etc.

### ISSUE THREAD

**Issue by svoyak** [mgp25/Chat-API-NET#10]
hi all!! Sometimes I got exceptions during send message. It look like BinTreeNodeReader->readListSize: Invalid token 86 or other digit after token. What it means? And how I can fix it? Thanks.

**Comment by mgp25** [comment]
@svoyak please post debug log and your program code.

Regards

**Comment by svoyak** [comment]
if (wa.ConnectionStatus == ApiBase.CONNECTION_STATUS.LOGGEDIN)
                {
                    //wa.SendGetClientConfig();
                    //wa.SendGetServerProperties();
                    wa.SendGetGroups();
                    //wa.GetAccountInfo();

                    //Waiting for answer SendGetGroups();
                    var t1 = Task.Factory.StartNew(() =>
                    {
                        while (true)
                        {
                            try
                            {
                                wa.PollMessages();
                                Thread.Sleep(100);
                            }
                            catch (Exception e)
                            {
                                   //In this place I got exception getgroups_wt = 10000
                            }
                        }
                    });
                    t1.Wait(getgroups_wt);
Thanks.

**Comment by mgp25** [comment]
@svoyak can you also post your debug log? by the way, use `pollMessage` instead of  `PollMessages`

**Comment by svoyak** [comment]
Reregister account with Wart solved this trouble, but why? I don't know..
