### ISSUE TITLE
token generation

### ISSUE THREAD

**Issue by Zedits22** [mgp25/Chat-API-NET#101]
Hi!
Token changed again
When the registration program indicates "old_version".
How to generate a new token?
How this problem to change token exclude?

**Comment by mgp25** [comment]
Read wiki
Regards

**Comment by Zedits22** [comment]
when i click wiki i have:

 "Welcome to the Chat-API-NET wiki!

Wikis provide a place in your repository to lay out the roadmap of your project, show the current status, and document software better, together."

what page you mean?

**Comment by Zedits22** [comment]
i read this one: https://github.com/WHAnonymous/Chat-API/wiki/Token-Generation
but when i can get this:
      $timestamp it's the release time of the app, it's inside the app. Changes in every version.

thank you

**Comment by Zedits22** [comment]
I downloaded the old and new versions ща WhatsApp client, and can not find where to get timestamp

**Comment by ricardoperovano** [comment]
I'm having the same problem, did you find the solution ? I'm using the .net version

**Comment by Zedits22** [comment]
timestamp 1447796090073 for 2.13.21

**Comment by ricardoperovano** [comment]
Great! but how did you get this timestamp ?

**Comment by Zedits22** [comment]
https://github.com/WHAnonymous/Chat-API/commit/4a176bfd453575f621a6a40218b1bf8b09e9d69b
