### ISSUE TITLE
not-authorised

### ISSUE THREAD

**Issue by vijaySurface** [mgp25/Chat-API-NET#106]
Hello,

I'm getting Not Authorized messages since this morning. I have checked if my number is blocked, but it was not. When I checked in smartphone app, it was working correct. What should be the reason behind this issue ?

**Comment by istoned** [comment]
I'm too.

**Comment by mgp25** [comment]
Network

**Comment by VivekSingh573** [comment]
I'm getting Not Authorized messages since this morning. before that i can send the Message, image , video, audio from C# winform code .

Why it Happen ?

Please any one Give me right WhatsappAPI.dll or any solution ,
Please

**Comment by kirilydk** [comment]
Whatsapp has updated its version, you have to update WhatsApi project to compile a new whatsapi.dll

Go to folder "Constants" and open the file "WhatsConstants.cs" then change:

		public const string WhatsAppVer = "2.13.9";
		public const string UserAgent = "WhatsApp/2.13.9 S40Version/14.26 Device/Nokia302";
