### ISSUE TITLE
NOt getting proper last seen in whatsapp

### ISSUE THREAD

**Issue by PankajPrashar** [mgp25/Chat-API-NET#107]
i am using

WhatSocket.Instance.OnGetLastSeen +=new WhatsEventBase.OnGetLastSeenDelegate(Instance_OnGetLastSeen);

WhatSocket.Instance.SendQueryLastOnline(whatsapp numner);

and i am using this

void Instance_OnGetLastSeen(string from, DateTime lastSeen)
{

            sw1.WriteLine("From # " + from + "# lastseen- " + lastSeen);
      }
But i not getting proper last seen. I will show randam last month time.

Can you help me please.

**Comment by mgp25** [comment]
Deprecated function see main repo
