### ISSUE TITLE
Not authorized - solved

### ISSUE THREAD

**Issue by danielst83** [mgp25/Chat-API-NET#108]
Hi everybody

Today I couldn't connect to WhatsApp, so I changed my local file WhatsConstants as following:

// Previous value: 2.12.96
public const string WhatsAppVer = "2.13.9";

// Previous value: WhatsApp/2.12.96 S40Version/14.26 Device/Nokia302
public const string UserAgent = "WhatsApp/2.13.9 S40Version/14.26 Device/Nokia302";

I tried to connect using the same password, but I got: not authorized.
Then I tryied to register again using voice option. Instead of making the call, it answered me with a new password.  Now everything is working.

Is anybody else facing the same problem?

Sorry for any English grammar mistakes...

**Comment by rflsouza** [comment]
It was the same with me!

When I'd Request Register showed " {"status":"fail","reason":"old_version"} "

I changed the const "WhatsAppVer and UserAgent " and it worked.

Hugs

**Comment by VivekSingh573** [comment]
ButI m not able to come out from this problem.
Since morning login not authorized.  before that I used everything to send
image,  video, audio.

Now I have problem from whatsappApi

**Comment by alijundi** [comment]
hi guys. It happened to me too last night! It seems that the solution of @danielst83  is right. I will have to check my app on Saturday though. Will keep you all informed then.

**Comment by kirilydk** [comment]
Where are whatsAppver and UserAgent values? I´m having this problem since morning and got no idea how you fixed it.

**Comment by kirilydk** [comment]
Found it :P

**Comment by kirilydk** [comment]
Big Big Big thank you it works!! :D:D
