### ISSUE TITLE
stream error: ack

### ISSUE THREAD

**Issue by andrewsub** [mgp25/Chat-API-NET#11]
Hi everyone,

Since I'm receiving "stream:error ack" too many times and this causes a disconnection, I was wondering, should the code stay as it is today, and disconnect whenever such an error is received? 

If I understand correctly, @mgp25 had promised a major update coming soon to fix this issue (am I right?), but until then, will it be wise to change the code temporarily (and localy) not to disconnect if the stream:error is about ack? Will it be a violation of WhatsApp's protocol?

Thanks

**Comment by mgp25** [comment]
Post your debug log and ill do a fix whenever i have time

Regards

**Comment by andrewsub** [comment]
Sorry, disregard this question, I didn't notice there is a new version regarding this problem.
