### ISSUE TITLE
Help me display the answer in a textbox please already tried 

### ISSUE THREAD

**Issue by bydario** [mgp25/Chat-API-NET#117]
Help me display the answer in a textbox please already tried everything and can not , and you know if she read the message

**Comment by bydario** [comment]
Windows Form...

**Comment by mgp25** [comment]
The first question is not API related. The second one: use event system

Regards

**Comment by bydario** [comment]
When I send a message to a person she receives the message more when not answer me the message in the textbox am using the example WhatsAppPort
