### ISSUE TITLE
is it bug in WhatsRegisterV2.cs

### ISSUE THREAD

**Issue by Zedits22** [mgp25/Chat-API-NET#118]
hi

this from wiki:

>Requesting code

>https://v.whatsapp.net/v2/code?in=*********&cc=**&id=%**%DC%E7%**%C*%A8%**%26%**%4F%35%**%B1%69%AF%**&lg=es&lc=ES&sim_mcc=214&sim_mnc=007&method=sms&token=*********TOKEN*********

>method: sms or voice
>in: phone number without country code
>cc: country code
>id: identity
>lg: Language (identified by checking sim_mnc and sim_mcc)
>lc: Language set in the device, if not found it will set zz
>token: token (used for requesting sms/voice code)
>sim_mcc: mcc of sim
>sim_mnc: mnc of sim

this from Register/WhatsRegisterV2.cs
>request = String.Format("https://v.whatsapp.net/v2/code?method={0}&in={1}&cc={2}&id={3}&lg={4}&lc={5}&token={6}&sim_mcc=000&sim_mnc=000", method, pn.Number, pn.CC, id, pn.ISO639, pn.ISO3166, token, pn.MCC, pn.MNC);

is it bug: **&sim_mcc=000&sim_mnc=000** ?

rgrds

**Comment by mgp25** [comment]
Its fine like that

Regards
