### ISSUE TITLE
sync problem

### ISSUE THREAD

**Issue by beljk** [mgp25/Chat-API-NET#12]
Dear @mgp25  ,,
i have three numbers and registered with the same salt using WART .. so when sync all numbers with them , is this means the numbers are friends ??? after that i send message from first number to other two numbers without sync contact then also get block ?? whats wrong ?....is there difference between sync before and after ?? Thanks for every thing dear @mgp25

**Comment by beljk** [comment]
@mgp25 @alijundi  Where are you guys ? :)

**Comment by alijundi** [comment]
You have to follow a certain procedure when you send messages. You cannot simply call send message and thats it. It is all documented in the wiki

**Comment by EgyptianM** [comment]
@alijundi 
there is nothing in the wiki 
can you explain some more?

**Comment by hpatel4u** [comment]
@beljk plz check this once.

https://github.com/WHAnonymous/Chat-API/wiki/WhatsAPI-Documentation#sending-a-message-contact-must-be-synced

**Comment by beljk** [comment]
@alijundi @hpatel4u 
 what is the deference between first login with all steps and other login with a few steps ????
 is this mean when my number first login I do all steps and when login again do steps for other login ???
