### ISSUE TITLE
 Receiving message

### ISSUE THREAD

**Issue by gousth** [mgp25/Chat-API-NET#120]
When I get the message :

        void wa_OnGetMessage(ProtocolTreeNode messageNode, string from, string id, string name, string message, bool receiptsent)
        {

        lststatus.items.add(message); }

the parameter message return this value:
 3��^!1�d�u�>�lGL�1��T�;ɿA�BbDM�X�!擊F

any one can help me with this problem , please?

thanks.

**Comment by mgp25** [comment]
Message is encrypted, search in closed issues

Regards
