### ISSUE TITLE
is it necessary: sendGetPrivacyBlockedList()

### ISSUE THREAD

**Issue by Zedits22** [mgp25/Chat-API-NET#123]
Hi. I continue to learn wiki
I hope to create a new issues right

this from wiki:

>**WhatsApp Workflow**

>Fist Login / Login

>$w->connect(); // Connects to WhatsApp

>$w->loginWithPassword(); // Login

>**$w->sendGetPrivacyBlockedList(); // Get our privacy list**
>...
>**$w->sendGetBroadcastLists(); // Get broadcasts lists**

Questions:
1. is it necessary metod **sendGetPrivacyBlockedList()** for first/next login?
2. is it necessary metod **sendGetBroadcastLists()** for first login?
3. is it necessary metod **sendGetProfilePicture()** for first login?
4. can server block number because there are no these methods?
thanks

**Comment by mgp25** [comment]
@Zedits22 it's recommended, we need to do the same as WhatsApp client

Regards

**Comment by Zedits22** [comment]
sorry but I have'nt found these methods in **chat-api-net**:
 - sendGetPrivacyBlockedList
 - sendGetBroadcastLists
 - sendGetProfilePicture

tell me please, where I can borrow them?

I think, answer to this question will eliminate newcomers issues :)

**Comment by mgp25** [comment]
You can port them from here: https://github.com/WHAnonymous/Chat-API

You can send a pull request later.

Regards

**Comment by Zedits22** [comment]
ok, i found some:

**sendGetPrivacyBlockedList** represented as **SendGetPrivacyList** in API
**sendGetProfilePicture** represented as **SendGetPhoto** or **SendGetPhotoIds** in API

and I think it will take developers:
```
public void SendGetBroadcastLists()
        {
            string id = TicketCounter.MakeId();
            var listsNode = new ProtocolTreeNode("list", null);
            var node = new ProtocolTreeNode("iq", new[] { new KeyValue("id", id), new KeyValue("type", "get"), new KeyValue("xmlns", "w:b"), new KeyValue("to", "s.whatsapp.net") },
                new ProtocolTreeNode("lists", null));
            this.SendNode(node);
        }
```
is it correct?
