### ISSUE TITLE
Encoding message error

### ISSUE THREAD

**Issue by Alex-Tar** [mgp25/Chat-API-NET#124]
Code 
this.fireOnGetMessage(node, node.GetAttribute("from"), node.GetAttribute("id"),
                                        node.GetAttribute("notify"), <b>System.Text.Encoding.UTF8.GetString(contentNode.GetData())</b>,
                                        autoReceipt);
make the unreadable message now. 
Example result: 3���!G�r�-(I3���%&WHGL�2n{��m8a!�,���*�N��-���z�OI�k:�&�Z�0R"B3 ! �[���R�0~1� �^�}��<�,a�ԏ�-%"^x���S���-t�J�;�h�8U(���0
Original message text: Test
Sended by original Android WhatsApp application. This issue from early December.

**Comment by mgp25** [comment]
This is because messages are being encrypted. Read closed issues

**Comment by Alex-Tar** [comment]
Sorry.
I read all the comments now and I understood correctly that there is no chance?

**Comment by mgp25** [comment]
@Alex-Tar i dont have enought time to implement all changes here. You can use the php API

**Comment by gousth** [comment]
@Alex-Tar  you solved ?.

**Comment by Alex-Tar** [comment]
No. I can't use php.
