### ISSUE TITLE
wa_OnGetMessage Encrypted Message

### ISSUE THREAD

**Issue by cfristofer** [mgp25/Chat-API-NET#129]
How do i get clear text  from whatsApp.OnGetMessage ?

**Comment by mgp25** [comment]
With this API you can't, use php one instead

**Comment by cfristofer** [comment]
Ok, i'm using ChatApi-Net, there's a solution for this problema in C# ??

**Comment by cfristofer** [comment]
I'm not lucky, the problem its the i'm trying to implement  a win service to get and send messages. Well  thanks for your help.

**Comment by cfristofer** [comment]
There's a way to get the key used to encrypt the text in android ??
