### ISSUE TITLE
Stream error: connection closed

### ISSUE THREAD

**Issue by splynde** [mgp25/Chat-API-NET#13]
Hello a few weeks ago i have closed connection problem after a few minutes I get `</ ack> </ stream: error> ` followed by the `connection closed` ...
I wonder how do you leave the 24/7 online bot ... my bot had been online only answering incoming messages ...

My code is currently so soon after loginsuccess it starts a loop sending sendping with a pause of a few seconds, I do not know what to do can help me friends ??

OnLoginSuccess:
```c#
this.Instance.SendGetPrivacySettings ();
this.Instance.SendGetPrivacySettings ();
this.Instance.SendActive ();
this.Instance.SendPing ();

KeepAlive:
while (! dispose)
{
Thread.Sleep (8000);
this.Instance.SendPing ();
}
```

**Comment by mgp25** [comment]
@splynde can you post your debug log?

**Comment by splynde** [comment]
<iq from="s.whatsapp.net" id="ping_1125" type="result"></iq>
<iq from="s.whatsapp.net" id="ping_1126" type="result"></iq>
<iq from="s.whatsapp.net" id="ping_1127" type="result"></iq>
<iq from="s.whatsapp.net" id="ping_1128" type="result"></iq>
<iq from="s.whatsapp.net" id="ping_1129" type="result"></iq>
<iq from="s.whatsapp.net" id="ping_1132" type="result"></iq>
<stream: error> <ack> </ ack> </ stream: error>

----
that's what you need?

**Comment by splynde** [comment]
I will make the program generate the log and post here ...

you can send me your skype or email? I want to propose you a kind of partnership if you are interested!

**Comment by splynde** [comment]
hi @mgp25 it is the debug log:

<\start from="s.whatsapp.net"><\/start>
<\stream:features><\/stream:features>
<\challenge>a��-{LC��1��U8s$��<\/challenge>
<\success t="1432284376" props="4" kind="free" status="active" creation="1426724086" expiration="1458260086">�4C�w�ި�����l���<\/success>
<\ib from="s.whatsapp.net">
<\offline count="0"><\/offline>
<\/ib>
<\iq from="s.whatsapp.net" id="getprivacy_0" type="result">
<\privacy>
<\category name="last" value="all"><\/category>
<\category name="status" value="all"><\/category>
<\category name="profile" value="all"><\/category>
<\/privacy>
<\/iq>
<\presence from="557199900815@s.whatsapp.net"><\/presence>
<\iq from="s.whatsapp.net" id="ping_2" type="result"><\/iq>
<\iq from="s.whatsapp.net" id="getprivacy_1" type="result">
<\privacy>
<\category name="last" value="all"><\/category>
<\category name="status" value="all"><\/category>
<\category name="profile" value="all"><\/category>
<\/privacy>
<\/iq>
<\iq from="s.whatsapp.net" id="ping_3" type="result"><\/iq>
<\iq from="s.whatsapp.net" id="ping_4" type="result"><\/iq>
<\iq from="s.whatsapp.net" id="ping_5" type="result"><\/iq>
<\iq from="s.whatsapp.net" id="ping_6" type="result"><\/iq>
<\iq from="s.whatsapp.net" id="ping_7" type="result"><\/iq>
<\iq from="s.whatsapp.net" id="ping_8" type="result"><\/iq>
<\iq from="s.whatsapp.net" id="ping_9" type="result"><\/iq>
<\iq from="s.whatsapp.net" id="ping_10" type="result"><\/iq>
<\iq from="s.whatsapp.net" id="ping_11" type="result"><\/iq>
<\iq from="s.whatsapp.net" id="ping_12" type="result"><\/iq>
<\iq from="s.whatsapp.net" id="ping_13" type="result"><\/iq>
<\iq from="s.whatsapp.net" id="ping_14" type="result"><\/iq>
<\iq from="s.whatsapp.net" id="ping_15" type="result"><\/iq>
<\iq from="s.whatsapp.net" id="ping_16" type="result"><\/iq>
<\iq from="s.whatsapp.net" id="ping_17" type="result"><\/iq>
<\iq from="s.whatsapp.net" id="ping_18" type="result"><\/iq>
<\iq from="s.whatsapp.net" id="ping_19" type="result"><\/iq>
<\iq from="s.whatsapp.net" id="ping_20" type="result"><\/iq>
<\iq from="s.whatsapp.net" id="ping_21" type="result"><\/iq>
<\iq from="s.whatsapp.net" id="ping_22" type="result"><\/iq>
<\iq from="s.whatsapp.net" id="ping_23" type="result"><\/iq>
<\iq from="s.whatsapp.net" id="ping_24" type="result"><\/iq>
<\iq from="s.whatsapp.net" id="ping_25" type="result"><\/iq>
<\iq from="s.whatsapp.net" id="ping_26" type="result"><\/iq>
<\iq from="s.whatsapp.net" id="ping_27" type="result"><\/iq>
<\iq from="s.whatsapp.net" id="ping_28" type="result"><\/iq>
<\iq from="s.whatsapp.net" id="ping_29" type="result"><\/iq>
<\iq from="s.whatsapp.net" id="ping_30" type="result"><\/iq>
<\iq from="s.whatsapp.net" id="ping_31" type="result"><\/iq>
<\iq from="s.whatsapp.net" id="ping_32" type="result"><\/iq>
<\iq from="s.whatsapp.net" id="ping_636" type="result"><\/iq>
<\iq from="s.whatsapp.net" id="ping_33" type="result"><\/iq>
<\iq from="s.whatsapp.net" id="ping_34" type="result"><\/iq>
<\iq from="s.whatsapp.net" id="ping_35" type="result"><\/iq>
<\iq from="s.whatsapp.net" id="ping_36" type="result"><\/iq>
<\iq from="s.whatsapp.net" id="ping_37" type="result"><\/iq>
<\iq from="s.whatsapp.net" id="ping_38" type="result"><\/iq>
<\iq from="s.whatsapp.net" id="ping_39" type="result"><\/iq>
<\iq from="s.whatsapp.net" id="ping_40" type="result"><\/iq>
<\stream:error> <\ack> <\/ack>  ...

**Comment by mgp25** [comment]
@splynde you are using an oudated code

Regards

**Comment by splynde** [comment]
I made several changes to this code, how do I know what the differences between the old and the new changed what  ??

I'll have to re-download the dll that repository Chat-API-NET and this will solve my problems?

**Comment by mgp25** [comment]
yes

**Comment by splynde** [comment]
OK thank you!

**Comment by splynde** [comment]
@mgp25 another doubt, excuse me, I have need to send sendping and sendactive at all times to keep online 24/7? If yes, what the wait in seconds between a sending and one for both?

what the time in seconds to while (true) {this.Instance.pollMessage (); Thread.Sleep (???); }
Can you show me what structure to keep online 24/7?
I thank you!

 - excuse me be speaking at a closed question, I do not know if it's wrong to do that, I'm new here
