### ISSUE TITLE
Some messages are not decrypted

### ISSUE THREAD

**Issue by rflsouza** [mgp25/Chat-API-NET#130]
Today I signed up a new number and messages are coming encrypted.

@mgp25 , I researched and found a problem in PHP reposted this December, from what I saw is the same situation, is that right?    If yes, I'm waiting for a new version, because I have no idea how I can help.

Similar in php: https://github.com/WHAnonymous/Chat-API/issues/1266

**Received in new number register:**  *(message in* **enc** *TAG)*
```
rx <message from="xxx1@s.whatsapp.net" type="text" id="xx117" t="x13" notify="x x">
rx  <enc v="1" type="pkmsg">3???!???
?X,0??1??Z?'?n?????
!?V'?h2?
mg?y??6
,9L?<
4?yN8V?G"B3
!y??A???j??~?CA?+?r?u????!R "?8L|?S?u?8[ ??9g?t?p!M(????0 </enc>
rx </message>
```
**Received in old number register:** *(message in* **body** *TAG)*
```
rx <message from="xxx1@s.whatsapp.net" type="text" id="xx8" t="1x95" notify="x x">
rx   <body>Oi..</body>
rx </message>
```

**Comment by mgp25** [comment]
@rflsouza .NET doesnt support E2E endcryption. Only the php API, btw its fixed.

Regards

**Comment by rflsouza** [comment]
@mgp25, sorry about my English, but I did not understand. In .NET there is no such problem, should work? *Because I had trouble today with a number.*

I got more information about this *number*, and that number had registered WhatsApp for *IOS*. I *deleted* the *account* and *registered again* and still keep getting encrypted messages to it. When I get the message comes TAG **enc**

**I did another test:** *I got a new other chip "that has never been registered with WhatsApp" And that worked usual, I received the message without encryption. I received on TAG body.*

**Comment by gastongiosue** [comment]
Hi All. Sorry, I'm new to GitHub and wanted to know if this issue is resolved, because I removed the account and register again, then I install Curve and Protobuf and still have the same problem.

**Comment by mgp25** [comment]
@gastongiosue wrong repo, i guess you are talking about Chat API php

**Comment by GHFoz** [comment]
Hello everybody, we have news ?
