### ISSUE TITLE
Incoming Messages are encrypted

### ISSUE THREAD

**Issue by KapteinBabbalas** [mgp25/Chat-API-NET#131]
Hi Guys, just noticed that my incoming messages are now encrypted for some reason.It started doing this a few hours ago, WhatsApp probably changed something.I also noticed that not all my numbers are affected but only some of them.

**Comment by mgp25** [comment]
@KapteinBabbalas Its normal, read other issues. The .NET API doesnt support E2E encryption, if you want to read encrypted messages use the php API

Regards

**Comment by ricardoperovano** [comment]
@KapteinBabbalas I have the solution for now, but i dont know for how long. you have to replace the respectives values on your WhatsAppApi.Settings.WhatsConstants class with this

public const string WhatsAppDigest = "xmpp/s.whatsapp.net";

        public const string WhatsAppHost = "c3.whatsapp.net";

        public const string WhatsAppRealm = "s.whatsapp.net";

        public const string WhatsAppServer = "s.whatsapp.net";

        public const string WhatsGroupChat = "g.us";

        public const string WhatsAppVer = "2.11.16";

        public const int WhatsPort = 443;

        public const string Device = "iPhone";

        public const string UserAgent = "WhatsApp/2.12.68 S40Version/14.26 Device/Nokia302";

        public static NumberStyles WhatsAppNumberStyle = NumberStyles.AllowLeadingSign | NumberStyles.AllowDecimalPoint;

        public static DateTime UnixEpoch = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc);


and then replace the respective value on WhatsAppApi.Register.WaToken with this

string token = "PdA2DJyKoUrwLw1Bg6EIhzh502dF9noR9uFCllGk1425519315543" + number;


remember to comment the old code, for me its working, but i dont know for how long. I think whatsapp will block iPhone too.

**Comment by ricardoperovano** [comment]
recompile the project and use the new whatsappapi.dll

**Comment by michaelqu** [comment]
@ricardoperovano  I got the same problem  yesterday ，and  iPhone will be block soon after

**Comment by ricardoperovano** [comment]
@michaelqu I think too, but now its working
