### ISSUE TITLE
How to set profile picture?

### ISSUE THREAD

**Issue by ivanlewis** [mgp25/Chat-API-NET#133]
How to set profile picture using the api?

**Comment by andrekat** [comment]
same here?

**Comment by andrekat** [comment]
well, i tried the function but it wont work /: i guess theres a problem with encryption .. could be ? 
getting exception: Exception thrown: 'WhatsAppApi.Helper.ConnectionException' in WhatsAppApi.dll 

but dont know where .. i guess its an empty exception block ?
