### ISSUE TITLE
message received in different format  

### ISSUE THREAD

**Issue by manthanmehta60** [mgp25/Chat-API-NET#138]
message received in 3!����C�%[l��>��k*˶�l<Z�-��C!�n�y��Ԁ�Y�r3��-�����+s��¡,"B3
!w��v�Q�@�9��Zw)�K�>���
&yw9 "�����xA�����l_M����Gd(���0��   format how can i convert into string format

Please help me i m stuck here .....

**Comment by gousth** [comment]
message is encrypted :/

**Comment by manthanmehta60** [comment]
how can i decrypt this

**Comment by manthanmehta60** [comment]
Please anyone give me solution for this

**Comment by mgp25** [comment]
Messages are encrypted, it required libaxolotl in order to support E2E encryption

Regards

**Comment by kunalsmehtajobs** [comment]
When will be the encryption decryption available in the api?
