### ISSUE TITLE
LastSeen

### ISSUE THREAD

**Issue by sebas0066** [mgp25/Chat-API-NET#140]
Hi, i'm tying to get the LastSeen from a number i call this method (i use asp.net visual basic)

contact = "xxxxxxxxxxxxxx"

Dim Manager As New WhatsUserManager()
        Dim wuser As WhatsUser

        wuser = Manager.CreateUser(contact, "Testct")
wa.SendQueryLastOnline(wuser.GetFullJid)
wa.pollmessages()

and i declare this:
AddHandler wa.OnGetLastSeen, AddressOf wa_OnGetLastSeen

and then i take the result:

    Public Sub wa_OnGetLastSeen(from As String, lastseen As DateTime)

        result = from & " - " & lastseen

    End Sub

i recive the result but i have two problems, first it takes too long to responde like 3 minutes or so, after its give me a wrong date and time like "1/1/0001 12:00 AM" but i'm using whatspp with that number.

any help please.

**Comment by mgp25** [comment]
@sebas0066 this is no longer supported by WA
