### ISSUE TITLE
Number getting blocked after adding participant in a group

### ISSUE THREAD

**Issue by gahlotkrishan** [mgp25/Chat-API-NET#143]
```javascript
//Sorry for posting this issue in php repository last time.

SENT: <iq id="1453315750-2" type="set" xmlns="w:g2" to="91766736xxxx-1453284749@g.us">
SENT:   <add>
SENT:     <participant jid="919x1xxxxx11@s.whatsapp.net"></participant>
SENT:   </add>
SENT: </iq>

RECVD: <stream:error>
RECVD:   <system-shutdown></system-shutdown>
RECVD: </stream:error>
```
If I query groups or send message to group then it's working fine but number got blocked immediately if I fire participant add/remove command. Please guide what's wrong, may be there's some protocol change for adding/removing participant!

**Comment by gahlotkrishan** [comment]
Working after updating the API

**Comment by ameralfaqeeh** [comment]
Dear Krishan,

Please help me can you good personal email.


thank you bro

On Mon, Feb 22, 2016 at 6:30 AM, gahlotkrishan <notifications@github.com>
wrote:

> Working after updating the API
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mgp25/Chat-API-NET/issues/143#issuecomment-186986171>.
>



-- 
*Best Regards,*

*      Amer AlFaqeeh*
         Software Engineering
         Business Intelligence Developer

*      Email:  *amer.alfaqeeh@hotmail.com
*      Email:  *amer.alfaqeeh@gmail.com

          Mobile:    +966-59-5205281
