### ISSUE TITLE
Is this repository no longer supported ?

### ISSUE THREAD

**Issue by VanDevos** [mgp25/Chat-API-NET#145]
Hello @mgp25 ,

Sorry to disturb you but I'm wondering is this repository no longer supported ?

Thanks!

**Comment by mgp25** [comment]
@VanDevos it is supported, and still active, but i wont do all the work if that is what are you trying to say. I don't have enought time to do everything in all my projects so i expect the users not only open issue but also contribute to the project, fix issues and improve things.

Regards
