### ISSUE TITLE
connection still timeout after a few minute

### ISSUE THREAD

**Issue by farisyusry** [mgp25/Chat-API-NET#15]
i just test using whatstest, the connection still timeout after a few minute.
i need to ping after a few minute to prevent connection timeout?

thank you

**Comment by mgp25** [comment]
debug log?

**Comment by farisyusry** [comment]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.


C:\Users\xx\Downloads\Chat-API-NET-master (2)\Chat-API-NET-master\WhatsTest\b
in\Release>WhatsTest.exe

tx <stream:features>
tx   <readreceipts></readreceipts>
tx   <groups_v2></groups_v2>
tx   <privacy></privacy>
tx   <presence></presence>
tx </stream:features>

tx <auth mechanism="WAUTH-2" user="x01x221254x">~?t??[???w8'?TT????T????r?u
-??F???</auth>

rx <start from="s.whatsapp.net"></start>

rx <stream:features></stream:features>

rx <success t="1432775841" props="4" kind="free" status="active" creation="14319
19929" expiration="1463455929">g??U[g?QeT!??????y?</success>

tx <presence name="faris"></presence>

tx <iq id="1432775841-1" type="get" xmlns="w" to="s.whatsapp.net">
tx   <props></props>
tx </iq>

rx <ib from="s.whatsapp.net">
rx   <offline count="0"></offline>
rx </ib>

rx <presence from="x01x221254x@s.whatsapp.net"></presence>

rx <iq from="s.whatsapp.net" id="1432775841-1" type="result">
rx   <props version="4">
rx     <prop name="timeout" value="300"></prop>
rx     <prop name="location" value="0"></prop>
rx     <prop name="readreceipts" value="1415214000"></prop>
rx     <prop name="qr" value="0"></prop>
rx     <prop name="groups_v2" value="1"></prop>
rx     <prop name="lists" value="1"></prop>
rx     <prop name="library" value="0"></prop>
rx     <prop name="audio" value="1"></prop>
rx     <prop name="checkmarks" value="0"></prop>
rx     <prop name="newmedia" value="0"></prop>
rx     <prop name="video_max_edge" value="960"></prop>
rx     <prop name="image_max_kbytes" value="5120"></prop>
rx     <prop name="image_quality" value="80"></prop>
rx     <prop name="image_max_edge" value="1280"></prop>
rx     <prop name="media" value="16"></prop>
rx     <prop name="broadcast" value="50"></prop>
rx     <prop name="max_subject" value="25"></prop>
rx     <prop name="max_participants" value="101"></prop>
rx     <prop name="max_groups" value="9999"></prop>
rx   </props>
rx </iq>



--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
after offline 

rx <iq from="s.whatsapp.net" id="1432775841-1" type="result">
rx   <props version="4">
rx     <prop name="timeout" value="300"></prop>
rx     <prop name="location" value="0"></prop>
rx     <prop name="readreceipts" value="1415214000"></prop>
rx     <prop name="qr" value="0"></prop>
rx     <prop name="groups_v2" value="1"></prop>
rx     <prop name="lists" value="1"></prop>
rx     <prop name="library" value="0"></prop>
rx     <prop name="audio" value="1"></prop>
rx     <prop name="checkmarks" value="0"></prop>
rx     <prop name="newmedia" value="0"></prop>
rx     <prop name="video_max_edge" value="960"></prop>
rx     <prop name="image_max_kbytes" value="5120"></prop>
rx     <prop name="image_quality" value="80"></prop>
rx     <prop name="image_max_edge" value="1280"></prop>
rx     <prop name="media" value="16"></prop>
rx     <prop name="broadcast" value="50"></prop>
rx     <prop name="max_subject" value="25"></prop>
rx     <prop name="max_participants" value="101"></prop>
rx     <prop name="max_groups" value="9999"></prop>
rx   </props>
rx </iq>

rx <presence from="x01x22225x0@s.whatsapp.net"></presence>

rx <chatstate from="x01x22225x0@s.whatsapp.net">
rx   <composing></composing>
rx </chatstate>
x01x22225x0@s.whatsapp.net is typing...

rx <message from="x01x22225x0@s.whatsapp.net" id="1432773777-140" type="text" t=
"1432775980" notify="Faris">
rx   <body>Chgg</body>
rx </message>
Message from Faris x01x22225x0@s.whatsapp.net: Chgg

tx <receipt to="x01x22225x0@s.whatsapp.net" id="1432773777-140" type="read"></re
ceipt>

rx <ack from="x01x22225x0@s.whatsapp.net" id="1432773777-140" class="receipt" ty
pe="read"></ack>

rx <presence from="x01x22225x0@s.whatsapp.net" type="unavailable" last="deny"></
presence>

**Comment by farisyusry** [comment]
no error/debug after offline. only showing this
![after offline](https://cloud.githubusercontent.com/assets/8154627/7851059/a40fb624-051c-11e5-83f1-0c9658a2c8c6.png)

**Comment by avenz0** [comment]
I also experience the same behaviour. Is sending ping prevent time out?

**Comment by nigharsh** [comment]
I tried pinging. No difference.

**Comment by MarcoScabbiolo** [comment]
I've experienced the same problem, eventually you'll loose the connection to WhatsApp after a period of time of inactivity. The only solution i've came across is to check the connection status every 3-5 minutes and restart it if the connection was lost. Hope it helps.

**Comment by nigharsh** [comment]
Pinging and Send Active helps. Try different time intervals. I have mine set to 30 seconds. 
Also I've scheduled my exe to restart every 15 minutes using a simple batch script.

**Comment by ivanlewis** [comment]
same problem here.. any solution for this?

**Comment by mgp25** [comment]
send ping, update nodes from Chat API and seck ack

Regards
