### ISSUE TITLE
steps to start using axoltol

### ISSUE THREAD

**Issue by kunalsmehtajobs** [mgp25/Chat-API-NET#150]
Hi.
Its a very good news that we have got the axoltol issue fixed. It will be great if anyone can guide us all to the steps we need to take to get it working. I believe we need to store the keys in the db or local store but not sure how to do that.

Thanks in advance
Kunal

**Comment by mgp25** [comment]
@kunalsmehtajobs take a look to https://github.com/mgp25/Chat-API/

You can see how its done

Regards

**Comment by GHFoz** [comment]
@kunalsmehtajobs i did it with SQLite in my version but my axoltol is not working, if you want, i can send to you the code to store and read the keys.

**Comment by kunalsmehtajobs** [comment]
Please share the link.

**Comment by GHFoz** [comment]
@kunalsmehtajobs  check [https://www.4shared.com/zip/4o5YcNSvba/Chat-API-NET-test.html](url)

**Comment by kunalsmehtajobs** [comment]
@Ghfoz, sorry but link seems broken. Can you resend?

Thanks
Kunal

**Comment by mgp25** [comment]
Send pull requests when ready

Regards
