### ISSUE TITLE
Compile Error by mycurve25519

### ISSUE THREAD

**Issue by MyKeySoftMK** [mgp25/Chat-API-NET#151]
Hello, 
i have download the master-branche today and want to test i can receive messages. But I can´t compile the mycurve25519-project.

The message: "File (Include) cannot be open: "pch.h": No such file or directory" - I found the mentioned file in the folder "Header Files"

I using Visual Studio 2015 Community (German Edition). Need I something other to succesfull compile?

Thanks for help

**Comment by kwailo888** [comment]
two issues could resolve this .. first make sure that your include path is correct to the project folder, second make sure that you set the precompiled header option to use exisgting not create then clean the previous compile and rebuild .. this should resolve the issue

**Comment by MyKeySoftMK** [comment]
Thanks for your reply. The first setting works fine.

Then I change the precompiles Header setting to "use existing" - but the error after build (cleanup before) is: File (precompiles Headerfile) cannot open: "Debug"pch.pch": No such file or directory

Sorry for my questions - but my programming skills are C# and VB.NET - so i don´t know what settings in VS2015 are important für C++. Thanks that you try to help me

**Comment by MyKeySoftMK** [comment]
So, I have found a solution to fix the project - now can I compile them

Now the WhatsAppPort can send messages to my smartphone - but if i answer then no messages is send revice in the chat-window. It answering/recivieng not implemented now?

CU
Michael

**Comment by alijundi** [comment]
Hey guys is the new commit working with encryption support? I see some problems according to above comment!

**Comment by kwailo888** [comment]
I think the version here isn't the latest code. I'm currently in Thailand on a work assignment so haven't had time to check. will put a pull request to  mpg25 this week to update the repository. meanwhile here's a working solution to compile against

https://github.com/kwailo888/AxolotlTestApp

this has been tested and is working in one of my production environments. sorry for the delay guys .. truly work first :)

**Comment by MyKeySoftMK** [comment]
Thanks for this important hint - now it works for my tests

**Comment by fernandobhz** [comment]
@MyKeySoftMK how you solve the problem... I have the same error here..

**Comment by Impavido85** [comment]
I open the solution with VS2015 but don't compile! Missing libaxolotl
Any Idea?

**Comment by kaank** [comment]
libaxolotl doesnt build

2016-03-07 16:48 GMT+02:00 Impavido85 <notifications@github.com>:

**Comment by Impavido85** [comment]
The solution it isnt' complete?

**Comment by kaank** [comment]
https://wha.tools/

2016-03-07 17:14 GMT+02:00 Impavido85 <notifications@github.com>:

**Comment by kaank** [comment]
Maybe this project stopped by whatsapp

2016-03-07 17:30 GMT+02:00 Kaan KARATAÇ <kaankaratac@gmail.com>:

**Comment by mahmoudelbaz** [comment]
@MyKeySoftMK  would you please tell us how you make it work because i use the same fix here but i  got error  "Cannot open file  dummy.lib  "
any help please

**Comment by Vishu24** [comment]
Any one  can suggest us how you make is work, I am also facing same issue "Cannot open precompiled header file: 'Debug\pch.pch': No such file or directory"

Thanks

**Comment by samuelg78** [comment]
U need to compile mycurve25519 ...make sure c++ is been installed, then follow mylibaxolotl,,,,that whatappapi then whatsTest..... one a t a time

**Comment by Vishu24** [comment]
Thanks for you help,

But not able to compile the project mycurve25519. Is there any setting that I have to do for compile project. I had tried with Precompiled Header - Use (/Yu).

**Comment by samuelg78** [comment]
the vs2015 compiled the mycurve25519 without any error....... maybe u can try download from https://github.com/kwailo888/AxolotlTestApp

**Comment by Joffers** [comment]
Thanks, that gets the code compiling but still getting ascii/weird characters in the whatsapp message and the following message

"Couldn't decrypt message id..." in AxolotlManager.cs, line 120

Any ideas?

**Comment by PriyankaIt** [comment]
mycurve25519 not compitible with framework 4.0
