### ISSUE TITLE
wa_OnGetMessage event not occurring

### ISSUE THREAD

**Issue by inornos** [mgp25/Chat-API-NET#152]
Hello mgp25
i have completely compile your latest code and successfully run whatstest project but wa_OnGetMessage event not occurring , i send message from android smartphone but whatstest project not receiving any my message so what i do please help me

**Comment by GKG4** [comment]
@inornos can you please help me what changes you did to run it?
As I tried by getting missing library errors, and unable to fix them.

**Comment by inornos** [comment]
follow this link https://github.com/mgp25/Chat-API-NET/issues/151
i was replace files from this https://github.com/kwailo888/AxolotlTestApp solution for missing lib
