### ISSUE TITLE
error  on build mycurve25519

### ISSUE THREAD

**Issue by mahmoudelbaz** [mgp25/Chat-API-NET#155]
i download the solution and i have errors with the mycurve25519 cpp project
"Cannot open include file: 'pch.h': No such file or directory"

**Comment by mahmoudelbaz** [comment]
i used the soolv on #151 
but now i have this error
Severity	Code	Description	Project	File	Line
Error	LNK1104	cannot open file 'dummy.lib'	mycurve25519	D:\whatsApp\Chat-API-NET-master\mycurve25519\mycurve25519\LINK	1

**Comment by kwailo888** [comment]
there's a folder called extra in the mycurve25519 project, makes sure there's a file called dummy.lib in this folder and ensure you've linked it correctly in the project. refer to the image attached here 
![dl](https://cloud.githubusercontent.com/assets/16788446/13836638/5f1d1462-ec3e-11e5-9c26-b7f188978d31.png)
