### ISSUE TITLE
ArgumentNullException on new version Feb 25, 2016, old version without encryption works fine

### ISSUE THREAD

**Issue by fernandobhz** [mgp25/Chat-API-NET#158]
System.ArgumentNullException was unhandled by user code
  HResult=-2147467261
  Message=Valor não pode ser nulo.
Nome do parâmetro: source
  ParamName=source
  Source=WhatsAppApi
  StackTrace:
       em WhatsAppApi.WhatsSendBase.processInboundData(Byte[] msgdata, Boolean autoReceipt) na C:\Users\Fernando\Downloads\Chat-API-NET-master\WhatsAppApi\Base\WhatsSendBase.cs:linha 318
       em WhatsAppApi.WhatsSendBase.pollMessage(Boolean autoReceipt) na C:\Users\Fernando\Downloads\Chat-API-NET-master\WhatsAppApi\Base\WhatsSendBase.cs:linha 74
       em WhatsAppApi.WhatsSendBase.PollMessages(Boolean autoReceipt) na C:\Users\Fernando\Downloads\Chat-API-NET-master\WhatsAppApi\Base\WhatsSendBase.cs:linha 60
       em WhatsAppPort.frmForm.ProcessMessages(Object sender, DoWorkEventArgs args) na C:\Users\Fernando\Downloads\Chat-API-NET-master\WhatsAppPort\frmForm.cs:linha 82
       em System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
       em System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
  InnerException:

**Comment by pablokerestezachi** [comment]
Guys? The last code works? Because I can´t decrypt the messages.

Saludos,
Pablo

**Comment by alijundi** [comment]
please check the testApp uploaded by @kwailo888

**Comment by fernandobhz** [comment]
On the 'WhatsTest' and on the 'WhatsAppPort' same error, using the 'WhatsAppApi'

It's necessary register the number on whatsapp again?

I tried with the old login info that works on old version.
