### ISSUE TITLE
SendMessageBroadcast image, audio, video not work only text

### ISSUE THREAD

**Issue by splynde** [mgp25/Chat-API-NET#16]
SendMessageBroadcast is not working for media except text, trying to send video image or audio connection drops and shows no debug log, can help me?

I am not trying to send spam and recipients have my number in the phonebook and both synchronized

@mgp25 help me ?

**Comment by alijundi** [comment]
If you run your sendbroadcast function in seperate thread than the main thread you should be fine. Works for me! The issue is with the upload data for all media types. Even send normal message with image will have the same issue.
