### ISSUE TITLE
 Strangers characters on decrypt message

### ISSUE THREAD

**Issue by pablokerestezachi** [mgp25/Chat-API-NET#160]
I send "Hola", so whats this strange characters on mi log.
![image](https://cloud.githubusercontent.com/assets/5023437/13650772/0abf71e2-e623-11e5-9f06-75086fcb1673.png)

**Comment by samuelg78** [comment]
You need to extract the message using regex.

**Comment by Vishu24** [comment]
I send "Good Morning", below are the character i received.
![image](https://cloud.githubusercontent.com/assets/12472833/13666896/d9ae60b0-e6d9-11e5-8f8f-3cd4d85624a2.png)

**Comment by mgp25** [comment]
Read closed issues. Is not that hard
