### ISSUE TITLE
no library

### ISSUE THREAD

**Issue by guishison** [mgp25/Chat-API-NET#162]
hi, i download and not has library mylibaxolotl.dll and WhatsAppApi.dll or i have a error. please help me pls

**Comment by kwailo888** [comment]
have you tried compiling the code?

**Comment by pablokerestezachi** [comment]
When we can get image decrypted? :)

Saludos,
Pablo

**Comment by kwailo888** [comment]
@pablokerestezachi currently working on this ... should be soon :)
