### ISSUE TITLE
Could not load file or assembly 'mycurve25519.dll' or one of its dependencies. The specified module could not be found.

### ISSUE THREAD

**Issue by inornos** [mgp25/Chat-API-NET#163]
Hello 
When i build all libraries and try to run on the other pc I'm getting this error **Could not load file or assembly 'mycurve25519.dll' or one of its dependencies. The specified module could not be found.**

I have install c++ and visual c++ redistribution 2015 but not working and giving this error please help me what i do for this error

**Comment by wahyuam** [comment]
try delete from reff, and add it again mycurve25519.dll

**Comment by inornos** [comment]
I'm trying to run the application on the another machine not development machine
i have successfully build all libraries on the development machine but want to run on other machine

**Comment by eaba** [comment]
@inornos  how where you able to build mycurve25519?

**Comment by viniciusvarzea** [comment]
I can compile successfully . But I can not run on the target machine , you can only run on the development machine. :(

**Comment by wahyuam** [comment]
I was succes to build it but the message still encrypted. And throw untrustedidentity.

**Comment by eaba** [comment]
i am getting `Error MSB3202: The project file "C:\a\1\s\..\XSocketsAgentView\XSocketsAgentView.csproj" was not found.`
what do i do?

**Comment by viniciusvarzea** [comment]
onyone can resolve this/

**Comment by viniciusvarzea** [comment]
?

**Comment by kwailo888** [comment]
here's a compiled version of the mycurve25519.dll in both 32bit and 64bit. use the one that matches you development environment. also make sure that you have the correct version of the net framework on your server to match .. it's compiled against dotnet 4.5 
[mycurve25519.zip](https://github.com/mgp25/Chat-API-NET/files/183611/mycurve25519.zip)

**Comment by jas35** [comment]
Facing same problem getting error message when run exe 
![c](https://cloud.githubusercontent.com/assets/15263789/13948351/94e0cf84-f045-11e5-86b0-dc1d73b169b3.png)

**Comment by p031985s** [comment]
Hi there...

I  have solved it compiling it with vs2012 forcing 64 bits, if you are using 32bits force it to 32 bits and all dll have to be 32 or all in 64.

On 64 bits
mycurve25519.dll 64bits
mylibaxolotl.dll 64bits
WhatsAppApi.dll 64bits
YourApp.exe 64Bits

On 32 Bits
mycurve25519.dll 32bits
mylibaxolotl.dll 32bits
WhatsAppApi.dll 32bits
YourApp.exe 32Bits

I hope it helps

**Comment by jas35** [comment]
Which dependencies (redistribution or program) are require to run visual c++ dll

**Comment by kwailo888** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=48145
