### ISSUE TITLE
Message received with extra characters

### ISSUE THREAD

**Issue by samuelg78** [mgp25/Chat-API-NET#164]
I had received message with extra characters.... the message should be "Ee123 7 6009 10-120"...instead it received in followings:

"\n\u0013Ee123 7 6009 10-120\u001c\u001c\u001c\u001c\u001c\u001c\u001c\u001c\u001c\u001c\u001c\u001c\u001c\u001c\u001c\u001c\u001c\u001c\u001c\u001c\u001c\u001c\u001c\u001c\u001c\u001c\u001c\u001c"

"\n\u0013Ee123 7 6009 10-120ggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggg"

"\n\u0013Ee123 7 6009 10-120�������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������"

"\n\u0010Ee123 7 6009 10-120\v\v\v\v\v\v\v\v\v\v\v"

"\n\u0013Ee123 7 6009 10-120BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB"

"\n\u0013Ee123 7 6009 10-12000000000000000000000000000000000000000000000000"

"\n\u0013Ee123 7 6009 10-12000000000000000000000000000000000"

How can i extract the correct message? I am able to extract the first 5 messages using regex but not the last 2 messages.

**Comment by kwailo888** [comment]
I'm guessing that these issues are related to non English character sets. if your getting this issue in the test environment I've uploaded can i suggest you try adding the following adjustment to the code in the ProcessChat function:

Console.OutputEncoding = System.Text.Encoding.GetEncoding("Cyrillic");
Console.InputEncoding = System.Text.Encoding.GetEncoding("Cyrillic");
and let me know it it solves the output input strange character problems.

**Comment by sanjoo88** [comment]
I am receiving totally encrypted message. 

The original message was 'Hello'. But I am receiving a totally different set of characters.

Here is the console output

================================================

rx <message from="919231xx01xx@s.whatsapp.net" type="text" id="AE80DC6E9CBF66950
8829FAF4D0CAA" t="1458636085" notify="Mr. X">
rx   <enc v="1" type="pkmsg" count="4">É?!?Hx7????J?X?(?????zX?9H!X
pf?sE~M??,?JB?4~?@{? L)?5`"B3
!??\?i?????H??4?<?OPn"?Bô? "?9???q`??p^m?????B??(????0?</enc>
rx </message>
info : Couldn't decrypt message id AE80DC6E9CBF669508829FAF4D0CAA from 919231970
144. Retrying.
Message from Mr. X 919231xx01xx@s.whatsapp.net: É?!?Hx7????J?X?(?????z
X?9H!Xpf?sE~M??,?JB?4~?@{? L)?5`"B3
!??\?i?????H??4?<?OPn"?Bô? "?9???q`??p^m?????B??(????0?


================================================


I am using the testing project which attached with API. Is there anything I am doing wrong ? Any help would be appreciated.

Thanks in advance.

**Comment by samuelg78** [comment]
@kwailo888 
Console.OutputEncoding = System.Text.Encoding.GetEncoding("Cyrillic");
 Console.InputEncoding = System.Text.Encoding.GetEncoding("Cyrillic");
 wa.PollMessages();

Resulted that it cannot received any message at all. Pls advice

**Comment by kwailo888** [comment]
the above code only changes the character sets for input and output in the console and does nothing to effect the code. I think your problem is elsewhere

**Comment by sanjoo88** [comment]
@kwailo888 are you able to get the received message with out unrecognized characters ?

do you think I am getting encrypted message because I am using a number which was register with different API previously.

**Comment by samuelg78** [comment]
@kwailo888 but my messages is all in alphabets and numbers.... sometimes i does not have extra characters. How to solve this problem?

**Comment by samuelg78** [comment]
@sanjoo88 do you received the message format as mine?

**Comment by sanjoo88** [comment]
I am receiving message with unrecognized characters..


The original message was 'Hello'. 
Received message : É?�!���?��Hx7????�J?�X?(?????z
X�?9H�!�X�pf?�sE~M??�,?JB?4~?@�{? L�)?5"B3 !�??\?i?????H��??4?�<?OPn"?Bô?���� "�?9�?�??q?�?p^m??�???B??(????�0?�

**Comment by samuelg78** [comment]
@sanjoo88 i think this is totally without decryption.... U using the latest code?

**Comment by sanjoo88** [comment]
@samuelg78 Yes I think so.. Yes I am using the latest code. did you fine any way to get the original text?
 Please share if you got anything...

**Comment by samuelg78** [comment]
@sanjoo88 The only way i can test is you send me your credential.

**Comment by sanjoo88** [comment]
@samuelg78 I don't think my credential will work. Cause we are from different country.. If you try my credential from yours country WhatsApp will block that anyway.

**Comment by samuelg78** [comment]
@sanjoo88 thats i am not sure about blocking.

**Comment by sanjoo88** [comment]
@samuelg78 I am 100% sure about it... :)

Anyway if you are able get the decrypted  message. Please share that code. It would help me a lot..

**Comment by samuelg78** [comment]
I am able to received the message but with extra characters..pls see above

**Comment by sanjoo88** [comment]
can you please share the whole project with me.. Maybe I am missing something.. At lest you are getting the original message within that.

**Comment by samuelg78** [comment]
U tried to download from https://github.com/kwailo888/AxolotlTestApp

**Comment by p031985s** [comment]
Hi there...

@sanjoo88 , no that is not, i am using my Colombian Numberr from a usa server...

I was using nikia s40, when mgp24 updated, i get same error, i can share my credentials, wrime by email... it is p031985s(@)yahoo.es.

**Comment by sanjoo88** [comment]
@samuelg78 Thank You.. At least I got the original message in it now.. :)

**Comment by samuelg78** [comment]
@sanjoo88 Do you have the extra characters that i had?

**Comment by sanjoo88** [comment]
@samuelg78 

The original message was 'Hello'

here is the received message

Hello??????????????????????????????????????????????????????????????????????????
????????????????????????????????????????????????????????????????????????????????
?????????

**Comment by kwailo888** [comment]
Add the following to the processchat function 

Console.OutputEncoding = System.Text.Encoding.GetEncoding("Cyrillic");
Console.InputEncoding = System.Text.Encoding.GetEncoding("Cyrillic");

**Comment by sanjoo88** [comment]
@kwailo888 

I have placed 

Console.OutputEncoding = System.Text.Encoding.GetEncoding("Cyrillic");
Console.InputEncoding = System.Text.Encoding.GetEncoding("Cyrillic");

In ProcessChat() function. 

 private static void ProcessChat(WhatsApp wa, string dst)
        {

            Console.OutputEncoding = System.Text.Encoding.GetEncoding("Cyrillic");
            Console.InputEncoding = System.Text.Encoding.GetEncoding("Cyrillic");
//other codes
-------------------------------
-------------------------------
}

But getting the same result. Is there any specific place I need to put that code? Please suggest.

Anyway thanks for the reply...:)

**Comment by p031985s** [comment]
@kwailo888, if we need it into s string, how do we do it?

Thank you.

**Comment by samuelg78** [comment]
@sanjoo88 But there is still no standard way to extract the message.... do note that sometime you will get message like mine (last 2 message).

**Comment by samuelg78** [comment]
@kwailo888 please let us know if we can received the message without the extra characters

**Comment by kwailo888** [comment]
This issues seems to only happen on non English language environments. I'm not facing this issue at all in my deployment.  This leads me to think it's a character set issue

**Comment by kwailo888** [comment]
I'll see if I can replicate it and suggest a solution

**Comment by samuelg78** [comment]
Thks,,,,, Waiting for your good news

**Comment by samuelg78** [comment]
But this still happen on my English language set on my iphone

**Comment by kwailo888** [comment]
On your iPhone?

**Comment by kwailo888** [comment]
It's has nothing to do with the phobe but is more related to the application development environment

**Comment by samuelg78** [comment]
but my application development environment is also english

**Comment by kwailo888** [comment]
Let me see if I xan identify the issue

**Comment by eaba** [comment]
I think the best thing to do here, for those facing the issue, is to drill down the code and add a break point to identify which line is adding this extra character.

**Comment by MHaendel** [comment]
I have the same problem with the testproject: http://i.imgur.com/P4cMg4u.png

**Comment by sanjoo88** [comment]
@samuelg78 I am trying to use regx at the moment to remove the unrecognized characters.. That wont be a 100% solution but at least that will work for me at the moment.

**Comment by MHaendel** [comment]
You might want to share your regexp?

**Comment by sanjoo88** [comment]
@MHaendel 

 message = Regex.Replace(message, @"\t|\n|\r", ""); //This is to remove tab,new line etc
 message = Regex.Replace(message, "[^\\w\\s.]*", ""); // To remove special character

Note this also remove '?','!','#' etc..

**Comment by MHaendel** [comment]
@sanjoo88 Ahh so very basic, for me, its always the first byte random, and the last one repeated several times. Does yours look equal?

**Comment by sanjoo88** [comment]
@MHaendel 

I did not get any repeated message sequence like that

The original message was 'Hello'
here is the received message
�Hello??????????????????????????????????????????????????????????????????????????
????????????????????????????????????????????????????????????????????????????????
?????????

So I used the above reqx which worked for me.

**Comment by MHaendel** [comment]
@sanjoo88 This applies to what I meant.

**Comment by sanjoo88** [comment]
ohhh.. Yes that is right.. I got it.. 

In the received message the first character is random. Once the message ends getting a another character repeating several times.

**Comment by samuelg78** [comment]
But if the sent message is "1234567890"....and the message received is "123456789000000000", there is no way to extract it.

**Comment by Joffers** [comment]
Hi

I used the below code to remove the ascii characters. Seems to work for me and keeps ?, etc in the message

File: WhatsSendBase.cs
Method: handleMessage(ProtocolTreeNode node, bool autoReceipt)
Line: 327
Extra info: replace the 'this.fireOnGetMessage(...' method just above the if( autoreceipt ) code line


byte[] baData = contentNode.GetData();

          StringBuilder sb = new StringBuilder();
          foreach( char c in baData.Select( b => (char)b ) )
          {
            if( ( c > '\u0020' && c < '\u007F' ) || c == 32 )
            {
              sb.Append( c );
            }
          }

          this.fireOnGetMessage( node, node.GetAttribute( "from" ), node.GetAttribute( "id" ),
                              node.GetAttribute( "notify" ), sb.ToString(),
                              autoReceipt );

**Comment by samuelg78** [comment]
@kwailo888 Hi, are you able to find a solution?

**Comment by eaba** [comment]
Hello @samuelg78, @kwailo888, @mgp25 see what I found on github: https://github.com/BayrakMustafa/WhatsApp-API-NET/commit/ed430e4785f2ba471d689596a662e62c1c101bc7

**Comment by mgp25** [comment]
@eaba if works, send a pull request

Regards

**Comment by eaba** [comment]
@mgp25 I am not the developer, i chanced upon it!
What do have to say, should the source be trusted?

**Comment by eaba** [comment]
My major issue is not the extra characters but decrypting, i try this if it works i will fork and then send a pull request!

**Comment by mgp25** [comment]
@eaba sure, thanks

**Comment by eaba** [comment]
Cant you contact the dude?

**Comment by samuelg78** [comment]
Does the PHP version have this extra characters issues?

**Comment by mgp25** [comment]
@samuelg78 nope, Chat API is way more updated than this

**Comment by samuelg78** [comment]
Is there a more detailed guide about how to install the CHAT API on windows? I am not a PHP/Linux guy and had been struggling to make Chat API to work..... I had installed xampp for windows but the php script is not running.

**Comment by samuelg78** [comment]
@mgp25 When i open the registerTool.php:
#################### # # # WA Register Tool # # # #################### Username (country code + number, do not use + or 00): 
Notice: Use of undefined constant STDIN - assumed 'STDIN' in C:\xampp\htdocs\Chat-API-master\examples\registerTool.php on line 14

Warning: fgets() expects parameter 1 to be resource, string given in C:\xampp\htdocs\Chat-API-master\examples\registerTool.php on line 14
Wrong number. Do NOT use '+' or '00' before your number

**Comment by mgp25** [comment]
@samuelg78 its a CLI script, for terminal usage. Open an issue in Chat API repo and read the wiki before

**Comment by akashgalaxy07** [comment]
I'm also having this same issue (couldn't decrypt message IDxxx) anyone found any solution?

**Comment by eaba** [comment]
Hello @mgp25 I have tried that repo and the result was a decrypted message with no extra characters.
I could not create a pull request as it was not my fork!

I want to read messages, mark them as received by the client but not read, how can i do this?

**Comment by samuelg78** [comment]
Had anyone fixed the error? Also anyone able to fix the new number registration tools?

**Comment by mgp25** [comment]
#176

**Comment by samuelg78** [comment]
@mgp25 Its still the same problem.

**Comment by MHaendel** [comment]
Problem still persists.
