### ISSUE TITLE
phone number is getting blocked by WhatsApp

### ISSUE THREAD

**Issue by sanjoo88** [mgp25/Chat-API-NET#168]
When registering using the API the phone number is getting blocked by the WhatsApp. In some cases its also showing banned while trying that number to register from phone using the WhatsApp app. Any idea ? or is there any way to generate password without getting blocked by the WhatsApp.

Thanks In advanced

**Comment by samuelg78** [comment]
I had also raised this problem.... but no reponse.

**Comment by Joffers** [comment]
Just got the same error. 

Using the WART tool I get a "Response = {"status":"fail","reason":"old_version"}" returned. 
Using the online service I get "Seems there was an error! Your number is blocked."

Any ideas?

**Comment by samuelg78** [comment]
This .net version is outdated.

**Comment by Joffers** [comment]
Thanks

I managed to get it to show the "blocked" response using the WART project by updating both the solution and the WhatsAppApi dll.

I am assuming now that it is blocked by WhatsApp and there is no way around this other than emailing them and asking them to unblock it?

Jeff

**Comment by samuelg78** [comment]
U will need to email them.
