### ISSUE TITLE
How to Compile Chat-API-NET?

### ISSUE THREAD

**Issue by akashgalaxy07** [mgp25/Chat-API-NET#173]
Hi all, How to compile the whole repository? I'm getting many errors about:
mycurve25519
and 
mylibaxolotl
both are not getting compiled. any solution/guidance?

**Comment by eaba** [comment]
Take a look at closed issues or search mycurve25519, you will find solutions:
#157, #163

**Comment by moody911** [comment]
Use VisualStudio2015 and add referance for mycurve25519.dll
and 
mylibaxolotl.dll
It will compile without any errors

**Comment by samuelg78** [comment]
Try this https://github.com/kwailo888/AxolotlTestApp

**Comment by akashgalaxy07** [comment]
thanks all for their help, I've compiled successfully

**Comment by akashgalaxy07** [comment]
Issue resolved
