### ISSUE TITLE
UntrustedIdentityException

### ISSUE THREAD

**Issue by eaba** [mgp25/Chat-API-NET#178]
Hi @mgp25 i am getting this `Tr.Com.Eimza.LibAxolotl.exceptions.UntrustedIdentityException`
I have moved my store to database, do i need to also implement database store for the AxolotlStore as i can see the exception is due to null, axolotl store not being able to find the identitykey.
Any Idea?

**Comment by mgp25** [comment]
@eaba for the moment chabge this function in axolotl:

```c#
        public override bool Equals(Object other)
        {
            if (other == null) return false;
            if (!(other is IdentityKey)) return false;

            return publicKey.Equals(((IdentityKey)other).getPublicKey());
        }
```

and make it always return true

**Comment by eaba** [comment]
@mgp25 thanks! I will let you know how it went.

**Comment by eaba** [comment]
Hello @mgp25 it works now, but I had to climb the stack to get it working like so:
```
/*if (!identityKeyStore.IsTrustedIdentity(remoteAddress.GetName(), theirIdentityKey))
            {
                throw new UntrustedIdentityException(remoteAddress.GetName(), theirIdentityKey);
            }*/
```
Is this okay for the moment?

**Comment by netomarquis** [comment]
I am getting this error every time I received the first message of the conversation... with the solution to make it return always true.

What could it be?

**Comment by eduardoboca** [comment]
I have the same problem as netomarquis (unable to decrypt message ID:xxxx on the frist message)
