### ISSUE TITLE
Error in runing

### ISSUE THREAD

**Issue by sardarn** [mgp25/Chat-API-NET#179]
Hi

When i want start the program and press Debug i get 3 erros:

Error	2	Metadata file 'Chat-API-NET-master\WhatsAppApi\bin\Debug\WhatsAppApi.dll' could not be found	Chat-API-NET-master\WhatsTest\CSC	WhatsTest
Error	3	Metadata file 'Chat-API-NET-master\WhatsAppApi\bin\Debug\WhatsAppApi.dll' could not be found	Chat-API-NET-master\WhatsAppPort\CSC	WhatsAppPort
Error	1	Metadata file 'Chat-API-NET-master\mylibaxolotl\bin\Debug\mylibaxolotl.dll' could not be found	Chat-API-NET-master\WhatsAppApi\CSC	WhatsAppApi

Thanks

**Comment by eaba** [comment]
Build the projects that could not be found individually first before running or building as a whole

**Comment by sardarn** [comment]
Hi

Please send me this files:

Chat-API-NET-master\WhatsAppApi\bin\Debug\WhatsAppApi.dll
Chat-API-NET-master\mylibaxolotl\bin\Debug\mylibaxolotl.dll

in my references there isn't mylibaxolotl.dll

Thanks

**Comment by GradariusYa** [comment]
UP
Please send me the file:
Chat-API-NET-master\mylibaxolotl\bin\Debug\mylibaxolotl.dll

**Comment by PriyankaIt** [comment]
Chat-API-NET-master\WhatsAppApi\bin\Debug\WhatsAppApi.dll
Chat-API-NET-master\mylibaxolotl\bin\Debug\mylibaxolotl.dll

in my references there isn't mylibaxolotl.dll
