### ISSUE TITLE
SendSync With not result

### ISSUE THREAD

**Issue by sebas0066** [mgp25/Chat-API-NET#18]
Hi i have problems with the sendsync when i do this function i not have any result on the onGetSyncResult.

Any idea of what is the cause?, i put a thread.Sleep but never get a result.

**Comment by sunil1909** [comment]
Hello Sebas0066. 
i think you are doing some mistake in syncing.

make sure you have number with country code and withou "+" or "0" double zeros.
let say india number start with +91 and we use 91xxxxxxxxx number.
so you can try sync(new string[]{"91xxxxxxxxxx","91yyyyyyyyy"});

any problem, let me know.
have a good day.
