### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by jusan92** [mgp25/Chat-API-NET#184]
Hi!
I'm trying to test the app and I'm getting this error: Login failed.

I have a real phone number and the password and following the trace I'm getting this error: Invalid length for a array or Base-64 string.

The error is in the Login function when it trying to send data.

Thanks.

**Comment by markdates** [comment]
Hi. You could solve the problem? It is running the API?
Tks!

**Comment by kant2002** [comment]
I have similar issue, and I correctly extract the password from the device.

**Comment by Cesar-Ofi** [comment]
Same error, can´t login, anyone know how to login?

**Comment by mgp25** [comment]
Outdated
