### ISSUE TITLE
the API does not recognize that a message was received (sometimes)

### ISSUE THREAD

**Issue by alijundi** [mgp25/Chat-API-NET#2]
When testing the new code in action I noticed that sometimes the API does not detect the incoming messages and the send does not receive a read receipt event when the option is on. @mgp25 can you please shed some light on that.

Thanks

**Comment by mgp25** [comment]
Post debug log

**Comment by alijundi** [comment]
hi @mgp25 it seems that the issue is related to the fact when I send messages to the API while it is offline and then I connect I am unable to see the messages received! even though I am getting the composing and paused notifications.

rx <chatstate from="962775454450@s.whatsapp.net">
rx   <composing></composing>
rx </chatstate>
9XXXXX454450@s.whatsapp.net is typing...

rx <chatstate from="962775454450@s.whatsapp.net">
rx   <paused></paused>
rx </chatstate>
9XXXXX454450@s.whatsapp.net stopped typing

and then the message is not received! I tried to login multiple times after which it started to work again. but it seems that it happens randomly.

**Comment by mgp25** [comment]
@alijundi false, its receiving messages perfectly

**Comment by alijundi** [comment]
I will double check and revert back

**Comment by alijundi** [comment]
below is the complete debug. at the end there is a stream error received after I login and there are some offline messages need to be delivered.

rx <receipt from="962775454450@s.whatsapp.net" id="1431089146-1" offline="0" typ
e="read" t="1431089172"></receipt>

tx <ack to="962775454450@s.whatsapp.net" class="receipt" id="1431089146-1"></ack
>

rx <receipt from="962775454450@s.whatsapp.net" id="1431089146-2" offline="0" typ
e="read" t="1431089179"></receipt>

tx <ack to="962775454450@s.whatsapp.net" class="receipt" id="1431089146-2"></ack
>

rx <presence from="962775454474@s.whatsapp.net"></presence>

rx <presence from="962775454450@s.whatsapp.net" type="unavailable" last="1431098
384"></presence>

rx <iq from="s.whatsapp.net" id="1431098437-1" type="result">
rx   <props version="4">
rx     <prop name="timeout" value="300"></prop>
rx     <prop name="location" value="0"></prop>
rx     <prop name="readreceipts" value="1415214000"></prop>
rx     <prop name="qr" value="0"></prop>
rx     <prop name="groups_v2" value="1"></prop>
rx     <prop name="lists" value="1"></prop>
rx     <prop name="library" value="0"></prop>
rx     <prop name="audio" value="1"></prop>
rx     <prop name="checkmarks" value="0"></prop>
rx     <prop name="newmedia" value="0"></prop>
rx     <prop name="video_max_edge" value="960"></prop>
rx     <prop name="image_max_kbytes" value="5120"></prop>
rx     <prop name="image_quality" value="80"></prop>
rx     <prop name="image_max_edge" value="1280"></prop>
rx     <prop name="media" value="16"></prop>
rx     <prop name="broadcast" value="50"></prop>
rx     <prop name="max_subject" value="25"></prop>
rx     <prop name="max_participants" value="101"></prop>
rx     <prop name="max_groups" value="9999"></prop>
rx   </props>
rx </iq>

rx <presence from="962775454450@s.whatsapp.net"></presence>

rx <chatstate from="962775454450@s.whatsapp.net">
rx   <composing></composing>
rx </chatstate>
962775454450@s.whatsapp.net is typing...

rx <chatstate from="962775454450@s.whatsapp.net">
rx   <paused></paused>
rx </chatstate>
962775454450@s.whatsapp.net stopped typing

rx <presence from="962775454450@s.whatsapp.net" type="unavailable" last="1431098
521"></presence>

rx <stream:error>
rx   <ack></ack>
rx </stream:error>

After all that the  API disconnects and would not receive any messages. If login/out a couple of times then everything goes back to normal. what do you think @mgp25?

Thanks.

**Comment by mgp25** [comment]
```xml
rx <stream:error>
rx   <ack></ack>
rx </stream:error>
```

ack missing, check code

**Comment by alijundi** [comment]
it seems that the receipt acks are not working fine. I keep receiving the same receipt with retry=4 and even though the API sends the ack WA does not recognize it.
```xml
rx <receipt from="962796638260@s.whatsapp.net" id="1431082537-29" retry="4" offl
ine="4" type="read" t="1431088174">
rx   <list>
rx     <item id="1431082537-27"></item>
rx   </list>
rx </receipt>
Message 1431082537-27 to 962796638260@s.whatsapp.net received by client

tx <ack to="962796638260@s.whatsapp.net" class="receipt" id="1431082537-29"></ac
```

After and even if I am logged in I can receive the chat/compose but no message is received. and in about 30 seconds I get a stream error and a disconnect.

**Comment by alijundi** [comment]
@mgp25 I just read your message. do you mean I need to do something or something needs to be done here? Thanks.

**Comment by alijundi** [comment]
I am not sure but I think I found a solution.

Update the following function:

 private void SendNotificationAck(ProtocolTreeNode node, string type = null)
        {
            string from = node.GetAttribute("from");
            string to = node.GetAttribute("to");
            string participant = node.GetAttribute("participant");
            string id = node.GetAttribute("id");

            List<KeyValue> attributes = new List<KeyValue>();
            if (!string.IsNullOrEmpty(to))
            {
                attributes.Add(new KeyValue("from", to));
            }
            if (!string.IsNullOrEmpty(participant))
            {
                attributes.Add(new KeyValue("participant", participant));
            }
            attributes.AddRange(new[] {
                new KeyValue("to", from),
                new KeyValue("class", node.tag),
                new KeyValue("id", id),
                new KeyValue("type",type)
            });
            ProtocolTreeNode sendNode = new ProtocolTreeNode("ack", attributes.ToArray());
            this.SendNode(sendNode);
        }

I added a new KeyValue of "type" and passed it the type of the ack.

it seems to work find. what do you think @mgp25 ?

**Comment by mgp25** [comment]
@alijundi i'll update later, send a pull request if you want with the following code:

```c#
 private void SendNotificationAck(ProtocolTreeNode node, string type = null)
        {
            string from = node.GetAttribute("from");
            string to = node.GetAttribute("to");
            string participant = node.GetAttribute("participant");
            string id = node.GetAttribute("id");
            string id = node.GetAttribute("type");

            List<KeyValue> attributes = new List<KeyValue>();
            if (!string.IsNullOrEmpty(to))
            {
                attributes.Add(new KeyValue("from", to));
            }
            if (!string.IsNullOrEmpty(participant))
            {
                attributes.Add(new KeyValue("participant", participant));
            }

            if (!string.IsNullOrEmpty(type))
            {
                attributes.Add(new KeyValue("type", type));
            }
            attributes.AddRange(new[] {
                new KeyValue("to", from),
                new KeyValue("class", node.tag),
                new KeyValue("id", id)
            });
            ProtocolTreeNode sendNode = new ProtocolTreeNode("ack", attributes.ToArray());
            this.SendNode(sendNode);
        }
```

**Comment by alijundi** [comment]
appreciate your quick response @mgp25. looks similar to mine but taking into consideration if it is null or not. I will try to do the pull request if I know how!

**Comment by mgp25** [comment]
Have you tried?

**Comment by alijundi** [comment]
works like a charm. 

 private void SendNotificationAck(ProtocolTreeNode node, string type = null)
        {
            string from = node.GetAttribute("from");
            string to = node.GetAttribute("to");
            string participant = node.GetAttribute("participant");
            string id = node.GetAttribute("id");
            string id = node.GetAttribute("type");

            List<KeyValue> attributes = new List<KeyValue>();
            if (!string.IsNullOrEmpty(to))
            {
                attributes.Add(new KeyValue("from", to));
            }
            if (!string.IsNullOrEmpty(participant))
            {
                attributes.Add(new KeyValue("participant", participant));
            }

            if (!string.IsNullOrEmpty(type))
            {
                attributes.Add(new KeyValue("type", type));
            }
            attributes.AddRange(new[] {
                new KeyValue("to", from),
                new KeyValue("class", node.tag),
                new KeyValue("id", id)
            });
            ProtocolTreeNode sendNode = new ProtocolTreeNode("ack", attributes.ToArray());
            this.SendNode(sendNode);
        }
