### ISSUE TITLE
How to get contact name?

### ISSUE THREAD

**Issue by EgyptianM** [mgp25/Chat-API-NET#20]
Hello mpg25
I'm trying to get the contact name to display in the chat window or in the contact list
I found an event with the name "WhatsAppApi.WhatsEventBase.OnGetContactName"
but didn't find a method to sendgetcontactname or anything like this.
can you tell me how to get it please?

thank you in advance

**Comment by mgp25** [comment]
You cant get nickname from a number, only when the user sends you a message

**Comment by EgyptianM** [comment]
and how can I get the nickname when the user sends me a message?
