### ISSUE TITLE
How to create group and add participants

### ISSUE THREAD

**Issue by beljk** [mgp25/Chat-API-NET#21]
@mgp25

**Comment by mgp25** [comment]
@beljk ctrl + F / cmd + F

https://github.com/mgp25/Chat-API-NET/blob/master/WhatsAppApi/WhatsApp.cs

**Comment by beljk** [comment]
Lol :dancer:

**Comment by jwjosefy** [comment]
For the God sake I've laughed loud here @mgp25 😂

Em qui, 11 de jun de 2015 13:44, beljk <notifications@github.com> escreveu:
