### ISSUE TITLE
WhatsApp WART throwing "Old Version" Error.

### ISSUE THREAD

**Issue by mayank-bhuvnesh** [mgp25/Chat-API-NET#210]
Hi

While generating password through API I am getting the below error at the following command

`**if (WhatsAppApi.Register.WhatsRegisterV2.RequestCode(txtPhoneNumber.Text, out password, out error, "sms"))**`

Error
**{"status":"fail", "reason":"old_version" **

Please find the screenshot for the same
![6](https://cloud.githubusercontent.com/assets/21168681/17847250/aabd4bbe-686a-11e6-8f3b-53191626064f.png)
![7](https://cloud.githubusercontent.com/assets/21168681/17847251/aac46cb4-686a-11e6-80b8-ff2523f4a697.png)

**Comment by mgp25** [comment]
@mayank-bhuvnesh update version

**Comment by mayank-bhuvnesh** [comment]
Hi I have tried this using updates veraion

**Comment by mayank-bhuvnesh** [comment]
And got this error

**Comment by victorinox1** [comment]
mayank-bhuvnesh, you worked? I still have the same error
