### ISSUE TITLE
WhatsApp WART throwing "Old Version" Error. #210

### ISSUE THREAD

**Issue by mayank-bhuvnesh** [mgp25/Chat-API-NET#211]
Hi
I am using the updated d version
Check issue 210
While generating password through API I am getting the below error at the following command

**if (WhatsAppApi.Register.WhatsRegisterV2.RequestCode(txtPhoneNumber.Text, out password, out error, "sms"))**

Error
*{"status":"fail", "reason":"old_version" *

Please find the screenshot for the same
6
7

**Comment by mgp25** [comment]
@mayank-bhuvnesh you need to update versions and user agent in constants. You can use this data: https://coderus.openrepos.net/whitesoft/whatsapp_scratch

Regards

**Comment by mayank-bhuvnesh** [comment]
@mgp25 I didn't get you..what are these constants???
