### ISSUE TITLE
Unable to create group

### ISSUE THREAD

**Issue by gahlotkrishan** [mgp25/Chat-API-NET#22]
Hi since past two days I'm not able to create a whatsapp group using .net API
Don't know what's wrong. Same API was working perfectly two days ago.
Is there any changes in latest version of whatsapp?

**Comment by mgp25** [comment]
Post debug log

**Comment by gahlotkrishan** [comment]
Thanks for the prompt reply

RECVD: <presence from="639427985460@s.whatsapp.net"></presence>

SENT: <iq id="create_group_0" type="set" xmlns="w:g2" to="g.us">
SENT:   <group action="create" subject="Aawara Pagal"></group>
SENT: </iq>

RECVD: <iq from="g.us" id="create_group_0" type="error">
RECVD:   <error code="400" text="bad-request"></error>
RECVD: </iq>

RECVD: <ib from="s.whatsapp.net">
RECVD:   <offline count="0"></offline>
RECVD: </ib>

**Comment by gahlotkrishan** [comment]
RECVD: presence from="639427985460@s.whatsapp.net"/presence

SENT: iq id="create_group_0" type="set" xmlns="w:g2" to="g.us"
SENT:   group action="create" subject="Aawara Pagal"/group
SENT: /iq

RECVD: iq from="g.us" id="create_group_0" type="error"
RECVD:   error code="400" text="bad-request"/error
RECVD: /iq

RECVD: ib from="s.whatsapp.net"
RECVD:   offline count="0"/offline
RECVD: /ib

**Comment by gahlotkrishan** [comment]
![error](https://cloud.githubusercontent.com/assets/6220871/8126050/a61e969a-1108-11e5-827b-a73407475ce5.PNG)

**Comment by gahlotkrishan** [comment]
![error](https://cloud.githubusercontent.com/assets/6220871/8126219/1f8d697e-110a-11e5-8a26-05eb5a2ad7d3.PNG)

**Comment by gahlotkrishan** [comment]
Sorry for multiple incorrect comments.
Please look into it
This is the final debug I got after a new group creation request

**Comment by mgp25** [comment]
@gahlotkrishan updated 

https://github.com/mgp25/Chat-API-NET/commit/356abee51e0cf8fd52ac48dd940432fefe016ecd

Use latest code

**Comment by gahlotkrishan** [comment]
Still getting bad request response 

![error](https://cloud.githubusercontent.com/assets/6220871/8126574/479351ce-110d-11e5-9437-cf30e68cdffe.PNG)

**Comment by mgp25** [comment]
@gahlotkrishan weird, it should look like this:

```xml
tx  <iq xmlns="w:g2" id="1" type="set" to="g.us">
tx    <create subject="Test">
tx      <participant jid="***@s.whatsapp.net"></participant>
tx    </create>
tx  </iq>
```

**Comment by gahlotkrishan** [comment]
Btw I didn't notice any difference b/t my request and yours.

My Current request/response

![error2](https://cloud.githubusercontent.com/assets/6220871/8127466/b53edc82-1114-11e5-8dd6-8a5fd43bb9ee.PNG)

Below is the function I'm using
![func](https://cloud.githubusercontent.com/assets/6220871/8127467/b58385f8-1114-11e5-9895-10425f1baa45.PNG)

**Comment by gahlotkrishan** [comment]
Finally it's working for

**Comment by wasimjee** [comment]
gahlotkrishan, 

when i create group, the group is being created successfully, but not getting the group id. please help
