### ISSUE TITLE
Login Fiald

### ISSUE THREAD

**Issue by MouawiaAltoma** [mgp25/Chat-API-NET#227]
after register, i tried to login
but give me this error
error "An established connection was aborted by the software in your host machine"

on

` private byte[] Socket_read(int length)
        {
            if (!socket.Connected)
            {
                throw new ConnectionException("Socket not connected");
            }

            var buff = new byte[length];
            int receiveLength = 0;
            do
            {
                try
                {
                    receiveLength = socket.Receive(buff, 0, length, 0);
                }
                catch (SocketException excpt)
                {
                    throw new ConnectionException(String.Format("Socket exception: {0}", excpt.Message), excpt);
                }

                //sleep to prevent CPU intensive loop
                if (receiveLength <= 0)
                {
                    System.Threading.Thread.Sleep(100);
                }
            }
            while (receiveLength <= 0);

            byte[] tmpRet = new byte[receiveLength];
            if (receiveLength > 0)
                Buffer.BlockCopy(buff, 0, tmpRet, 0, receiveLength);
            return tmpRet;
        }`

**Comment by mgp25** [comment]
An established connection was aborted by the software in your host machine. You are trying to login from two diff places
