### ISSUE TITLE
How to send message via group ???

### ISSUE THREAD

**Issue by beljk** [mgp25/Chat-API-NET#23]
after create group with participate .. what the best way to get Group id then how to send message to group ?
@mgp25

**Comment by sunil1909** [comment]
Hello beljk,
the best way to get group id is to call SendGetGroups(); method.

when you call this method, whatsapp will fire OnGetGroups(WaGroupInfo[] groups); event.

catch/write your code in this event such that you get all group details that you created before.
it include group name, id ,creation date etc.

i hope above mention details are clear to you.
any problem let me know.
have a good day.
