### ISSUE TITLE
cannot login

### ISSUE THREAD

**Issue by mazzica1** [mgp25/Chat-API-NET#234]
i updated the constants to : 
WhatsAppVer = "2.17.174";
UserAgent = "WhatsApp/2.17.174 Android/4.3 Device/Xiaomi-HM_1SW";
and token
var classesMd5 = "5PhjPwAEWaaPFD4h3nM0hA=="; //   2.17.174

and tried register and it worked :) 
but when i try login it is not working :( any suggest?

**Comment by mgp25** [comment]
The code it outdated

Regards

**Comment by Vishu24** [comment]
can you share latest code link?
