### ISSUE TITLE
Register says old_version

### ISSUE THREAD

**Issue by matiaskusack** [mgp25/Chat-API-NET#235]
Hi, I'm getting an error message when I try to Register using

`var codeRequested = WhatsAppApi.Register.WhatsRegisterV2.RequestCode(pn, out code, out request, out response, "sms");`

The error is
> {"login":"34XXXXXXXXX","status":"fail","reason":"old_version"}

Is this Project still working?

**Comment by mgp25** [comment]
https://github.com/mgp25/Chat-API/issues/2116
