### ISSUE TITLE
Number Registration Status : fail, reason :Old Version

### ISSUE THREAD

**Issue by angelgarcia7** [mgp25/Chat-API-NET#237]
When try registration i get the same error: 
{\"login\":\"PHONE_NUMBER\",\"status\":\"fail\",\"reason\":\"old_version\"}

Any suggest or there is solution or workaround for this issue? Thank you.

Regards.

**Comment by mgp25** [comment]
https://github.com/mgp25/Chat-API/issues/2116

Regards
