### ISSUE TITLE
Sync issue

### ISSUE THREAD

**Issue by sunil1909** [mgp25/Chat-API-NET#26]
after sync my personal number from api, i am trying to send broadcast message from my personal number to api number, but api not receiving message.

i think, api lacking incoming broacast message from other or sync function not saving number in server contact.

please check it.

any one observed the same problem and have any solution please reply here.

Regards,
Sunil Kumar

**Comment by sunil1909** [comment]
@mgp25  hello,
you marked as closed, but i didn't got solution about sync.

i am just saying that even we sync number, we dont receove broadcast message from other people.

sending broadcast message from personal phone  to api number ... but api not getting broadcast message.

by this bug, i can say that, api just sync but do not store number on whatsapp server, and due to this, not receiving broadcast message from others.

please look this bug.
thanks

**Comment by hpatel4u** [comment]
@sunil1909 If i am not wrong, broadcast message will received to those who have been added your sender number in his contact list and he must sync that number.

Plz try that once..
