### ISSUE TITLE
Compile error on WhatsApp.cs

### ISSUE THREAD

**Issue by jmf70** [mgp25/Chat-API-NET#27]
Hello, when I try to compile the WhatsAppApi project I get this error in WhatsApp.cs file:
it can't convert implicitly 'System.Collections.Generic.IEnumerable<WhatsAppApi.Helper.ProtocolTreeNode>' type to WhatsAppApi.Helper.Protocol.TreeNode.
Already exists and explicit conversion  (translate from the Spanish)

Thanks

**Comment by mgp25** [comment]
@jmf70 i'll check, i haven't tested anything in c# since may

**Comment by jmf70** [comment]
@mgp25 Hi, i've fixed it:
var child = new ProtocolTreeNode("create", new[] { new KeyValue("subject", subject) }, new ProtocolTreeNode[] { (ProtocolTreeNode) participant });

Thx
