### ISSUE TITLE
invalid token size received

### ISSUE THREAD

**Issue by alijundi** [mgp25/Chat-API-NET#3]
I receive tokens that are of size 9 which cause the exception to be thrown. Any ideas why?

```C#
 protected int readListSize(int token)
        {
            int size = 0;
            if (token == 0)
            {
                size = 0;
            }
            else if (token == 0xf8)
            {
                size = this.readInt8();
            }
            else if (token == 0xf9)
            {
                size = this.readInt16();
            }
            else
            {
                throw new Exception("BinTreeNodeReader->readListSize: Invalid token " + token);
            }
            return size;
        }
```

**Comment by alijundi** [comment]
it seems that the invalid token size exception above occurs after the following debug messages:

tx <presence type="active"></presence>
A first chance exception of type 'System.Exception' occurred in WhatsAppApi.dll
DEBUG: System.Exception: MAC mismatch on index 0! 99 != 145
   at WhatsAppApi.Helper.KeyStream.DecodeMessage(Byte[] buffer, Int32 macOffset, Int32 offset, Int32 length) in c:\Work\VMShared\TECO_WA_API\NEW CODE

**Comment by mgp25** [comment]
Yes, ill update it this weekend. If you want port it from Chat API

**Comment by alijundi** [comment]
will do. just please direct me to the function that needs to be ported by commenting on this issue with a link. Thanks @mgp25

**Comment by mgp25** [comment]
Post full code and debug log and i will fix it in a couple hours

Regards

**Comment by mgp25** [comment]
Try last commit, send me feedback, send me your code and debug log so i can improve the code

Regards

**Comment by alijundi** [comment]
hi @mgp25 I tried the last commit and at random events. I noticed when I send the sync contact to check if users are WA users I get the problem I mentioned before.

I looked the event viewer where my app is supposed to be running all the time and I find out that my app gets terminated. the below is registered in the event log.

Application: TECO_WA.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception
Stack:
   at WhatsAppApi.Helper.BinTreeNodeReader.readListSize(Int32)
   at WhatsAppApi.Helper.BinTreeNodeReader.nextTreeInternal()
   at WhatsAppApi.Helper.BinTreeNodeReader.nextTree(Byte[], Boolean)
   at WhatsAppApi.WhatsSendBase.processInboundData(Byte[], Boolean)
   at WhatsAppApi.WhatsSendBase.pollMessage(Boolean)
   at WhatsAppApi.WhatsSendBase.PollMessages(Boolean)
   at TECO_WA.Form1.<ConnectWA>b__19(System.Object)
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.Run


Any ideas on why this is happening? Thanks.

**Comment by mgp25** [comment]
@alijundi post code and request. Please quote output and code

**Comment by alijundi** [comment]
@mgp25 I appreciate your assistance but I do not have an output. The App terminates and all the debug is lost! how should I proceed?

**Comment by mgp25** [comment]
@alijundi change debug to true, run it in terminal

**Comment by alijundi** [comment]
@mgp25 I understand what you are saying. But what I am trying to say is that I see the debug and all is fine for 3-5 hours and then all of a sudden the app terminates and the all the debug is lost with it. now if I run it in the debugger I get the exception (throw new Exception("BinTreeNodeReader->readListSize: Invalid token " + token); thrown!

I think I will run it tomorrow on the debugger and when I get this exception I will copy and paste the log and post it here. please be patient.

**Comment by alijundi** [comment]
@mgp25  Below is the debug information that leads to invalid token received. Is it useful?

rx <stream:error>
rx   <system-shutdown></system-shutdown>
rx </stream:error>
Connection LOST
DEBUG: 
tx <stream:features>
tx   <readreceipts></readreceipts>
tx   <groups_v2></groups_v2>
tx   <privacy></privacy>
tx   <presence></presence>
tx </stream:features>
DEBUG: 
tx <auth mechanism="WAUTH-2" user="962775454474">n?6?|?2A?zc?!p??3?DEBUG: 
rx <s.whatsapp.net></s.whatsapp.net>
DEBUG: 
tx <presence type="active"></presence>
DEBUG: 
tx <presence type="active"></presence>
DEBUG: 
tx <stream:features>
tx   <readreceipts></readreceipts>
tx   <groups_v2></groups_v2>
tx   <privacy></privacy>
tx   <presence></presence>
tx </stream:features>
DEBUG: 
tx <auth mechanism="WAUTH-2" user="962775454474">?w?A|?2A?zc?!p??3?DEBUG: 
rx <s.whatsapp.net></s.whatsapp.net>
DEBUG: 
tx <presence type="active"></presence>
Error Connecting
DEBUG: 
tx <stream:features>
tx   <readreceipts></readreceipts>
tx   <groups_v2></groups_v2>
tx   <privacy></privacy>
tx   <presence></presence>
tx </stream:features>
DEBUG: 
tx <auth mechanism="WAUTH-2" user="962775454474">?1I|?2A?zc?!p??3?DEBUG: 
rx <s.whatsapp.net></s.whatsapp.net>
tx <presence type="active"></presence>
DEBUG: 
tx <stream:features>
tx   <readreceipts></readreceipts>
tx   <groups_v2></groups_v2>
tx   <privacy></privacy>
tx   <presence></presence>
tx </stream:features>
DEBUG: 
tx <auth mechanism="WAUTH-2" user="962775454474">??3?|?2A?zc?!p??3?DEBUG: 
rx <s.whatsapp.net></s.whatsapp.net>
DEBUG: 
tx <presence type="active"></presence>
Sending Active......
A first chance exception of type 'System.Net.Sockets.SocketException' occurred in System.dll
A first chance exception of type 'WhatsAppApi.Helper.ConnectionException' occurred in WhatsAppApi.dll
A first chance exception of type 'System.Net.Sockets.SocketException' occurred in System.dll
A first chance exception of type 'System.Exception' occurred in WhatsAppApi.dll
A first chance exception of type 'WhatsAppApi.Helper.ConnectionException' occurred in WhatsAppApi.dll
Error Connecting
DEBUG: 
tx <stream:features>
tx   <readreceipts></readreceipts>
tx   <groups_v2></groups_v2>
tx   <privacy></privacy>
tx   <presence></presence>
tx </stream:features>
DEBUG: 
tx <auth mechanism="WAUTH-2" user="962775454474">??O|?2A?zc?!p??3?DEBUG: 
rx <s.whatsapp.net></s.whatsapp.net>
tx <presence type="active"></presence>
A first chance exception of type 'System.Net.Sockets.SocketException' occurred in System.dll
A first chance exception of type 'WhatsAppApi.Helper.ConnectionException' occurred in WhatsAppApi.dll
A first chance exception of type 'System.Net.Sockets.SocketException' occurred in System.dll
A first chance exception of type 'WhatsAppApi.Helper.ConnectionException' occurred in WhatsAppApi.dll
A first chance exception of type 'System.Exception' occurred in WhatsAppApi.dll
tx <stream:features>
tx   <readreceipts></readreceipts>
tx   <groups_v2></groups_v2>
tx   <privacy></privacy>
tx   <presence></presence>
tx </stream:features>
tx <auth mechanism="WAUTH-2" user="962775454474">?a4	|?2A?zc?!p??3?DEBUG: 
rx <s.whatsapp.net></s.whatsapp.net>

**Comment by alijundi** [comment]
@mgp25 what do you think?
