### ISSUE TITLE
Cannot send image... please help

### ISSUE THREAD

**Issue by Zedits22** [mgp25/Chat-API-NET#30]
Hi!

I added a button on frmUserChat, and tried to send image when button click:

private void button1_Click(object sender, EventArgs e)
        {
            byte[] imagedata = File.ReadAllBytes("C:\\TEMP\\1.jpg");
            WhatSocket.Instance.SendMessageImage(this.user.WhatsUser.GetFullJid(),imagedata,WhatsAppApi.ApiBase.ImageType.JPEG);
        }

but programm don't answer after click button.

several times was an exception: BinTreeNodeReader->readListSize: Invalid token 172 
and other value of token

i tried change string in UploadFile():
            //while (this.uploadResponse == null && i <= 10)
            while (this.uploadResponse == null && i <= 50)
but no result... image not send. but it's ok with send text messages.

please help me.
maybe you have an c# example.

If i need to see printdebug, show me how it turn on.

Excuse my english

**Comment by Zedits22** [comment]
i tried:

            //while (this.uploadResponse == null && i <= 300)
            while (this.uploadResponse == null)
            {
                i++;
                //this.pollMessage();
            }

and it's OK. Why?

**Comment by netomarquis** [comment]
Same problem that I solved here: https://github.com/mgp25/Chat-API-.NET/issues/34#issuecomment-120677172

**Comment by Zedits22** [comment]
not same....   i add to = GetJID(to); but with this.pollMessage(); not work...

**Comment by Zedits22** [comment]
i think,  i must change metod UploadFile... line this.pollMessage(); must be in other stream (thread)...
