### ISSUE TITLE
SendSetImage not working

### ISSUE THREAD

**Issue by netomarquis** [mgp25/Chat-API-NET#31]
Hi, I am trying to set the image of my WhatsApp number using the API..

But method SendSetImage isnt working.. I dont get any errors but doesnt change the picture either

**Comment by yndmai45** [comment]
check the minimum image size, for me is working well

**Comment by netomarquis** [comment]
can you send me your method and what parameters you pass?

**Comment by yndmai45** [comment]
public static byte[] BitmapImageToByte(Image img)
        {
            ImageConverter converter = new ImageConverter();
            return (byte[])new ImageConverter().ConvertTo(img, typeof(byte[]));
        }

Instance.SendSetPhoto(number, BitmapImageToByte(pictureBox1.Image));

**Comment by netomarquis** [comment]
Thanks... number you pass your whatsapp sender number, right?

Your SendSetPhoto are just like these method?

 public void SendSetPhoto(string jid, byte[] bytes, byte[] thumbnailBytes =
null)
        {
            string id = TicketCounter.MakeId();

            bytes = this.ProcessProfilePicture(bytes);

            var list = new List<ProtocolTreeNode> { new
ProtocolTreeNode("picture", null, null, bytes) };

            if (thumbnailBytes == null)
            {
                //auto generate
                thumbnailBytes = this.CreateThumbnail(bytes);
            }

            //debug
            System.IO.File.WriteAllBytes("pic.jpg", bytes);
            System.IO.File.WriteAllBytes("picthumb.jpg", thumbnailBytes);

            if (thumbnailBytes != null)
            {
                list.Add(new ProtocolTreeNode("picture", new[] { new
KeyValue("type", "preview") }, null, thumbnailBytes));
            }
            var node = new ProtocolTreeNode("iq", new[] { new
KeyValue("id", id), new KeyValue("type", "set"), new KeyValue("xmlns",
"w:profile:picture"), new KeyValue("to", GetJID(jid)) }, list.ToArray());
            this.SendNode(node);
        }

2015-07-12 20:47 GMT-03:00 yndmai45 <notifications@github.com>:

> public static byte[] BitmapImageToByte(Image img)
> {
> ImageConverter converter = new ImageConverter();
> return (byte[])new ImageConverter().ConvertTo(img, typeof(byte[]));
> }
>
> Instance.SendSetPhoto(number, BitmapImageToByte(pictureBox1.Image));
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mgp25/Chat-API-NET/issues/31#issuecomment-120774248>.
>



-- 
Salvador Neto
Mobile: +55 15 98166-0094
neto.marquis@gmail.com
www.zonezero.com.br

Consultor .NET

**Comment by yndmai45** [comment]
yes, number off sender

**Comment by netomarquis** [comment]
Ok.. Not working here yet :(

Can you send your body method?

public void SendSetPhoto(string jid, byte[] bytes, byte[] thumbnailBytes =
null)

2015-07-12 20:52 GMT-03:00 yndmai45 <notifications@github.com>:

> yes, number off sender
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mgp25/Chat-API-NET/issues/31#issuecomment-120774439>.
>



-- 
Salvador Neto
Mobile: +55 15 98166-0094
neto.marquis@gmail.com
www.zonezero.com.br

Consultor .NET

**Comment by yndmai45** [comment]
public void SendSetPhoto(string jid, byte[] bytes, byte[] thumbnailBytes = null)
        {
            string id = TicketCounter.MakeId();

            bytes = this.ProcessProfilePicture(bytes);

            var list = new List<ProtocolTreeNode> { new ProtocolTreeNode("picture", null, null, bytes) };

            if (thumbnailBytes == null)
            {
                //auto generate
                thumbnailBytes = this.CreateThumbnail(bytes);
            }

            //debug
            System.IO.File.WriteAllBytes("pic.jpg", bytes);
            System.IO.File.WriteAllBytes("picthumb.jpg", thumbnailBytes);

            if (thumbnailBytes != null)
            {
                list.Add(new ProtocolTreeNode("picture", new[] { new KeyValue("type", "preview") }, null, thumbnailBytes));
            }
            var node = new ProtocolTreeNode("iq", new[] { new KeyValue("id", id), new KeyValue("type", "set"), new KeyValue("xmlns", "w:profile:picture"), new KeyValue("to", GetJID(jid)) }, list.ToArray());
            this.SendNode(node);
        }

**Comment by netomarquis** [comment]
Worked! Thanks

2015-07-12 20:56 GMT-03:00 yndmai45 <notifications@github.com>:

> public void SendSetPhoto(string jid, byte[] bytes, byte[] thumbnailBytes =
> null)
> {
> string id = TicketCounter.MakeId();
>
>         bytes = this.ProcessProfilePicture(bytes);
>
>         var list = new List<ProtocolTreeNode> { new ProtocolTreeNode("picture", null, null, bytes) };
>
>         if (thumbnailBytes == null)
>         {
>             //auto generate
>             thumbnailBytes = this.CreateThumbnail(bytes);
>         }
>
>         //debug
>         System.IO.File.WriteAllBytes("pic.jpg", bytes);
>         System.IO.File.WriteAllBytes("picthumb.jpg", thumbnailBytes);
>
>         if (thumbnailBytes != null)
>         {
>             list.Add(new ProtocolTreeNode("picture", new[] { new KeyValue("type", "preview") }, null, thumbnailBytes));
>         }
>         var node = new ProtocolTreeNode("iq", new[] { new KeyValue("id", id), new KeyValue("type", "set"), new KeyValue("xmlns", "w:profile:picture"), new KeyValue("to", GetJID(jid)) }, list.ToArray());
>         this.SendNode(node);
>     }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mgp25/Chat-API-NET/issues/31#issuecomment-120774584>.
>



-- 
Salvador Neto
Mobile: +55 15 98166-0094
neto.marquis@gmail.com
www.zonezero.com.br

Consultor .NET
