### ISSUE TITLE
Verify if number have whatsapp

### ISSUE THREAD

**Issue by netomarquis** [mgp25/Chat-API-NET#32]
Hi, What is the better way to verify if a number have whatsapp?

I am using `SendQueryLastOnline` to verify if returns any kind of date but I cant found a better way atm.

**Comment by yndmai45** [comment]
Instance.SendSync(new string[] { number }, ApiBase.SyncMode.Full, ApiBase.SyncContext.Background);

**Comment by yndmai45** [comment]
void Instance_OnGetSyncResult(int index, string sid, Dictionary<string, string> existingUsers, string[] failedNumbers)
        {
            //existingUsers
            //failedNumbers
        }

**Comment by Vishu24** [comment]
@netomarquis is your SendQueryLastOnline working properly?

**Comment by choudharyprateek** [comment]
I need to check number exist with whatsapp or not?
I have tried with this function
public static string RequestExist(string phoneNumber, string id = null)
but "json response is incorrect"
What should i do? Help me...!

**Comment by WHAnonymous** [comment]
As @yndmai45 has said, use sync

**Comment by choudharyprateek** [comment]
I am unable to use it. Can you please help me?
I have an excel sheet of numbers and I just need to create a filter for whatsapp registered numbers.
Thanks
