### ISSUE TITLE
keep bot online 24*7

### ISSUE THREAD

**Issue by mohitbajaj1234** [mgp25/Chat-API-NET#33]
How to keep my bot online 24*7

**Comment by hannydan** [comment]
I beleive you should add  wa_OnDisconnect, such as:

static void wa_OnDisconnect(Exception ex = null)
        {
           
            wa.Connect();
            string datFile = getDatFileName(Sender);
            byte[] nextChallenge = null;
            if (File.Exists(datFile))
            {
                try
                {
                    string foo = File.ReadAllText(datFile);
                    nextChallenge = Convert.FromBase64String(foo);
                }
                catch (Exception) { };
            }
            wa.Login(nextChallenge);
            ProcessChat(wa, WhatsAppApi.cs.Constants.TARGET);
        }
