### ISSUE TITLE
I need get groups

### ISSUE THREAD

**Issue by Zedits22** [mgp25/Chat-API-NET#34]
Hi!

I need to get groups. 

WhatSocket.Instance.SendGetGroups(); - this line only sends request for groups
if I understand correctly, then I have to call: WhatSocket.Instance.PollMessages();
this should lead to the activation of event: onGetGroups();
but the execution of the method PollMessages() hangs all... on step return Socket_read(length); (metod ReadData).

please, tell me how to get a list of groups, right?

**Comment by Zedits22** [comment]
i add lines

    case "/getgroups":
              wa.SendGetGroups();
              break;
    case "/getgroupsown":
              wa.SendGetOwningGroups();
              break;

into switch (command)

and have results:

/getgroupsown

tx <iq id="1437137679-2" type="get" xmlns="w:g2" to="g.us">
tx   <list type="owning"></list>
tx </iq>

rx <iq from="g.us" id="1437137679-2" type="error">
rx   <error code="400" text="bad-request"></error>
rx </iq>
/getgroups

tx <iq id="1437137679-3" type="get" xmlns="w:g2" to="g.us">
tx   <list type="participating"></list>
tx </iq>

rx <iq from="g.us" id="1437137679-3" type="error">
rx   <error code="400" text="bad-request"></error>
rx </iq>


please, tell me how to get a group list?

**Comment by JulioImolesi** [comment]
look at https://github.com/mgp25/Chat-API-NET/issues/56 
=]

**Comment by mgp25** [comment]
https://github.com/mgp25/Chat-API-NET/commit/8e07c510d2db2108f19d922f10187c01b0271d70

**Comment by Zedits22** [comment]
thanks
