### ISSUE TITLE
blocked using bot 24/7

### ISSUE THREAD

**Issue by yndmai45** [mgp25/Chat-API-NET#38]
I'm using the API as 24/7 bot to respond to several people at the same time, I am now getting the message "not-authorized" I tried to re-register and received the message, status: fail, reason: blocked.
how can I put the bot not to be blocked? what I need to send to each User simultaneously?

**Comment by yndmai45** [comment]
- there is something wrong, how can I improve?
my code receive and reply:

public void ReplayText(string to, string msg, bool last = true)
        {
            new System.Threading.Tasks.Task(() =>
            {
                Thread.Sleep(500);
                this.Instance.SendQueryLastOnline(WhatsApp.GetJID(to));
                Thread.Sleep(300);
                this.Instance.SendPresenceSubscriptionRequest(WhatsApp.GetJID(to));
                Thread.Sleep(300); 
                this.Instance.SendComposing(WhatsApp.GetJID(to));
                Thread.Sleep(2000);
                this.Instance.SendPaused(WhatsApp.GetJID(to));
                Thread.Sleep(300);
                this.Instance.SendMessage(WhatsApp.GetJID(to), msg);

                if (Sessions.ContainsKey(Fnx.ClearJid(to)))
                {
                    if (last)
                        Sessions[Fnx.ClearJid(to)].LastMsg = msg;
                    Sessions[Fnx.ClearJid(to)].ReceiveSend = true;
                }

                }).Start();
        }


 private void Instance_OnGetMessage(ProtocolTreeNode messageNode, string from, string id, string name, string message, bool receipt_sent)
        {
            new System.Threading.Tasks.Task(() =>
            {
              //reply to from
               ReplayText(from, "text reply...");
             }).Start();
        }

**Comment by vovanb** [comment]
We have same problem.
What is the solution?

Sincerely,
Vladimir

**Comment by mgp25** [comment]
@yndmai45 @vovanb any kind of bulk sending / receiving will be blocked by WhatsApp, no matter if it's spam or not, when you manage huge data, WhatsApp will block you.

**Comment by vovanb** [comment]
No I am not using bulk sending - the reply sent manually by live agent

On Thu, Jul 23, 2015 at 11:18 AM, mgp25 <notifications@github.com> wrote:

> @yndmai45 <https://github.com/yndmai45> @vovanb
> <https://github.com/vovanb> any kind of bulk sending / receiving will be
> blocked by WhatsApp, no matter if it's spam or not, when you manage huge
> data, WhatsApp will block you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mgp25/Chat-API-NET/issues/38#issuecomment-124018829>.
>



-- 
Sincerely,
Vladimir

**Comment by yndmai45** [comment]
thanks for the answer @mgp25 

what is the solution?
place users in a queue and not send ack reading?
if I put a greater delay time to read and answer and send SendUnsubscribeHim before responding to another User solve the blocking problem?

some command sent when it leaves the chat screen and goes to the historical conversations, and when you open a new chat screen?

**Comment by yndmai45** [comment]
someone who can help? I am willing to share part of the profit of this project who can help me to stay stable
