### ISSUE TITLE
SendPing - Not Work

### ISSUE THREAD

**Issue by rflsouza** [mgp25/Chat-API-NET#4]
I try to use SendPing, but return is wrong:

### Request
tx `<iq id="1431146635-3" type="get">`
tx  ` <ping xmlns="w:p"></ping>`
tx `</iq>`
### Return:
rx `<iq from="5511994977477@s.whatsapp.net" id="1431146635-3" type="error">`
rx  ` <error code="501" text="feature-not-implemented"></error>`
rx `</iq>`

## I change SendPing To:
```
public void SendPing()
{
   string id = "ping_" + TicketCounter.MakeId();
   var child = new ProtocolTreeNode("ping", null);
   var node = new ProtocolTreeNode("iq", new[] { new KeyValue("id", id), new KeyValue("xmlns", "w:p"), new KeyValue("type", "get"), new KeyValue("to", "s.whatsapp.net") }, child);           
    this.SendNode(node);
}
```
### Request
tx `<iq id="ping_1431145948-2" xmlns="w:p" type="get" to="s.whatsapp.net">`
tx  ` <ping></ping>`
tx `</iq>`
### Return:
rx `<iq from="s.whatsapp.net" id="ping_1431145948-2" type="result"></iq>`

**Comment by alijundi** [comment]
Thanks @rflsouza
