### ISSUE TITLE
Receiving Messages in WhatsAppPort

### ISSUE THREAD

**Issue by Mystpot** [mgp25/Chat-API-NET#42]
Hi,

Please forgive me if this is an ignorant question, I've run the console application and I can send and receive messages fine. However, I would like to be able to use this application in its GUI form and I am relatively new to programming. I've logged into the GUI, added my user, and sent a message to my phone which worked fine, and when I respond the message receives 2 blue ticks which implies the current "number" has read the message, but I am not sure how to display that message in the textbox. If anyone could point me in the right direction I would be very grateful!

**Comment by EgyptianM** [comment]
you need to handle this event

`wa.OnGetMessage += wa_OnGetMessage;`

**Comment by bydario** [comment]
Help me display the answer in a textbox please already tried everything and can not
