### ISSUE TITLE
Can't find  WhatsAppAPI.dll ??

### ISSUE THREAD

**Issue by mrrcomp** [mgp25/Chat-API-NET#44]
Hi 

I downloaded the zip and when I try to run it I get error
 Error	1	Metadata file 'C:\Users\admin7\Chat-API-NET-master\Chat-API-NET-master\WhatsAppApi\bin\Debug\WhatsAppApi.dll' could not be found	C:\Users\admin7\Chat-API-NET-master\Chat-API-NET-master\WhatsAppPort\CSC	WhatsAppPort

Where do i get this ?

**Comment by WHAnonymous** [comment]
@mrrcomp compile the project, use WhatsTest as an example

**Comment by messry** [comment]
R U STILL HAS ERROR
IF U R
then go to 
properties
                Build Events    and    Debug
and delete the command

it'll be work 

than you
