### ISSUE TITLE
Cryptography 

### ISSUE THREAD

**Issue by eduardo-bressan** [mgp25/Chat-API-NET#49]
Are you receiving cryptography text messages? How I translate the message?

**Comment by WHAnonymous** [comment]
@eduardo-bressan it's explained in https://github.com/WHAnonymous/Chat-API

You can follow the same procedure here

**Comment by eduardo-bressan** [comment]
I tried, but I awful in PHP, no one wrote in .NET?

**Comment by WHAnonymous** [comment]
@eduardo-bressan you dont need PHP, read the wiki there is documentation there... Anyway...:

Remove your account and using another identity register from zero your account, that should work. And if you have a friend with a started conversation, ask him to remove and add you again.

That will fix all your issues

**Comment by eduardo-bressan** [comment]
Thanks, I will try this and read the Wiki anyway.

Do you know if that project it's already decrypting the text? It seems that it is doing...

**Comment by WHAnonymous** [comment]
@eduardo-bressan that project is the same as this one, we are avoiding encrypted messages, we only manage plaintext messages, thats why you have to do that workarround if your number comes from an android device

**Comment by faculuna** [comment]
Hi, i have the same problem, register again the number with another identity, erase the conversation and generate a new and now 90% of the messages that recieve are encrypted.
