### ISSUE TITLE
Compilation error after download solution.

### ISSUE THREAD

**Issue by wlnaim** [mgp25/Chat-API-NET#50]
Error	1	Cannot implicitly convert type 'System.Collections.Generic.IEnumerable<WhatsAppApi.Helper.ProtocolTreeNode>' to 'WhatsAppApi.Helper.ProtocolTreeNode'. An explicit conversion exists (are you missing a cast?)	C:\Proyectos\CazaFugas\Chat-API-NET-master\Chat-API-NET-master\WhatsAppApi\WhatsApp.cs	450	125	WhatsAppApi

![image](https://cloud.githubusercontent.com/assets/1175397/9700086/f7923e2c-53bc-11e5-8954-f683ebd95a00.png)

I just changed the code to:

var child = new ProtocolTreeNode("create", new[] { new KeyValue("subject", subject) }, new ProtocolTreeNode[] { (ProtocolTreeNode) participant });

And now it compile and works nice.

Regards.

**Comment by WHAnonymous** [comment]
@wlnaim send a pull request and ill merge

Regards
