### ISSUE TITLE
 I receive whatsapp message is in encrypted format

### ISSUE THREAD

**Issue by shafiur1** [mgp25/Chat-API-NET#53]
Hi, 
  I am using Chat-API-Net  and  receive message is in encrypted so can you please help me.
 Message revived in below format.
 3���!���:'�����CEe�х�/z��`7�\QEf!�x�#N>�צ��"}ٱ�Q5dn[��רV�}

I did not find the solution in #109 Issue.

Regards
Shafiur

**Comment by faculuna** [comment]
Hi, i have the same problem, register again the number with another identity, erase the conversation and generate and now my messages recieve encrypted and now 90% of the messages that recieve are encrypted.

**Comment by shafiur1** [comment]
Hi mgp25,
Any solution please.

Regards
Shafiur

**Comment by faculuna** [comment]
I use the method getDeleteAccount, after with the wart 1.2.2 register the number again and the messages for the new numbers not are encrypted, but the old numbers sending encrypted, continue send encryptwd.
Test this.
Sory for my english.
Regards!!
Facundo

**Comment by shafiur1** [comment]
Thanks You Resolved it

**Comment by mohamedfady** [comment]
Dears, where could i find the getDeleteAccount method . and for registration i am using WART 1.8.2.2 is it OK
