### ISSUE TITLE
SendGetGroups() not rising events

### ISSUE THREAD

**Issue by wasimjee** [mgp25/Chat-API-NET#55]
after calling  SendGetGroups(); method. is not rising or firing OnGetGroups(WaGroupInfo[] groups); event.

**Comment by mgp25** [comment]
@wasimjee you need to bind it + paste and quote your code properly

**Comment by wasimjee** [comment]
I did same

My code 


wa.OnGetGroups += wa_OnGetGroups;

void wa_OnGetGroups(WaGroupInfo[] groups)
        {
            MessageBox.Show("got");           
        }


But not getting
