### ISSUE TITLE
SendGetGroups() not rising events

### ISSUE THREAD

**Issue by wasimjee** [mgp25/Chat-API-NET#56]
after calling `SendGetGroups();` method. is not rising or firing `OnGetGroups(WaGroupInfo[] groups);` event.

My code

```c#
    wa.OnGetMessage += wa_OnGetMessage;

    void wa_OnGetGroups(WaGroupInfo[] groups)
        {
           MessageBox.Show("got");            
        }


            wa.SendCreateGroupChat("HelloTest2", mylist);
               
             wa.SendGetGroups();
             wa.SendGetOwningGroups(); 
```

**Comment by wasimjee** [comment]
Sir please provide a solution

**Comment by JulioImolesi** [comment]
I got the same problem, follows the debug:


SENT:
<quote>
`<iq id="1442960962-1" type="get" xmlns="w:g2" to="g.us"`>
  `<list type="participating"`>`</list`>
`</iq`></quote>
 
RECEIVED:
<quote>
`<iq from="g.us" type="error" id="1442960962-1"`>
  `<error code="400" text="bad-request"`>`</error`>
`</iq`></quote>

**Comment by JulioImolesi** [comment]
While I was comparing the sent data with Php version I've found the solution:
at <b>public void SendGetGroups(string id, string type)</b>
replace the 
<quote><b>var child = new ProtocolTreeNode("list", new[] { new KeyValue("type", type) });</b> </quote>
by
<quote><b>var child = new ProtocolTreeNode(type, null);</b>
</quote>

**Comment by mgp25** [comment]
@JulioImolesi send a pull request

**Comment by mgp25** [comment]
https://github.com/mgp25/Chat-API-NET/commit/8e07c510d2db2108f19d922f10187c01b0271d70
