### ISSUE TITLE
Getting encrypted message

### ISSUE THREAD

**Issue by jaysonroni** [mgp25/Chat-API-NET#57]
Yesterday for some reason i Re-registered my number with WART and after that we received encypted (junk) message, i dont know why and how this happing with us.. bcoz before register this was work fine... pls help us.. we receive message as below

3���!a�{4�$}T{X���R�pS@���I7�
^!�\�P��W�DR%7F�=��B�+��"B3
!���L��,�0s�U0%��t�J0�BY7��

**Comment by mgp25** [comment]
@jaysonroni register with a different password (salt)

**Comment by jaysonroni** [comment]
We already tried that , but not getting solutions.. pls help us
