### ISSUE TITLE
Getting encrypted message

### ISSUE THREAD

**Issue by jaysonroni** [mgp25/Chat-API-NET#58]
Yesterday for some reason i Re-registered my number with WART and after that we received encypted (junk) message, i dont know why and how this happing with us.. bcoz before register this was work fine... pls help us.. we receive message as below

3������!�a�{�4�$}T{��X�����R�pS@���I7�
^�!��\�P��W��DR%7F���=���B�+�����"B3
!������L��,�0s���U0%��t�J�0�BY7��

We already tried with new password but yet getting solutions, and also changed
using resource "S 40-2.12.11-433" as we found in some forum... so kindly help me in this matter

**Comment by H4Code** [comment]
i have this problem too

**Comment by yniv** [comment]
same here! any solution?

**Comment by eduardo-bressan** [comment]
For aught I know, haven't a solution yet, but on te another project in PHP they are writing the algorithm to decrypt.

**Comment by almusalhi** [comment]
I have the same Issue. 
encrypted message. :( 

plz help

**Comment by mgp25** [comment]
Read Chat API issues and wiki, there will be support for this in Chat API, but it wont for this C# API (Sorry i dont have enought time)
