### ISSUE TITLE
Sync contact take long time in poolmessages 

### ISSUE THREAD

**Issue by beljk** [mgp25/Chat-API-NET#6]
@mgp25 the problem still found

I want to sync contact and here is my code
```c#
private void button1_Click(object sender, EventArgs e)
 {
 string[] num={"201018106101","201010432512","201281214102","201004412644","201000967204","201002639112"};
 if (!this.CheckLogin("20121241****", "Niy969EGhSijtgrPD4m9Ur4cig0=", "Adv"))
 {
            MessageBox.Show("Failed login");
            return;

        }
        MessageBox.Show("suc login");
        WhatSocket.Instance.SendSync(num, WhatsAppApi.ApiBase.SyncMode.Full, WhatsAppApi.ApiBase.SyncContext.Background, 0, true);
        WhatSocket.Instance.PollMessages();

        MessageBox.Show("Verification done!");
    }
    private void wa_OnGetSyncResult(int index, string sid, Dictionary<string, string> existingUsers, string[] failedNumbers)
    {
        //txt(String.Format("Sync result for {0}:", sid));
        foreach (KeyValuePair<string, string> item in existingUsers)
        {
            if (textBox1.Text.Length == 0)
            {
                textBox1.Text = item.Key.Substring(1);
            }
            else
            {
                textBox1.Text += "\r\n" + item.Key.Substring(1);
            }
        }

        foreach (string item in failedNumbers)
        {
            if (textBox2.Text.Length == 0)
            {
                textBox2.Text = item.Substring(1);
            }
            else
            {
                textBox2.Text = "\r\n" + item.Substring(1);
            }
        }
    }
```

then when run the app number login and send sync ok but in poolmessages its take a long time without result 
 Thanks

**Comment by hpatel4u** [comment]
@beljk remove the WhatSocket.Instance.PollMessages(); and try once.

**Comment by beljk** [comment]
@hpatel4u still no result I change my code to and still found

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading;
using System.Windows.Forms;
using WhatsAppApi.Helper;
using WhatsAppApi.Response;
using System.Threading;
using System.Globalization;
using System.Security.Cryptography;

namespace WhatsAppPort
{
    public partial class Checkconta : Form
    {
        string identity = string.Empty;
        string password;
        private string[] WaCertThumbprints = {
                                                 "AC4C5FDEAEDD00406AC33C58BAFD6DE6D2424FEE", 
                                                 "738F92D22B2A2E6A8A42C60964B93FCCB456957F",
                                                 "155906D29D14DF2A54F039F6E170C2A7F97EEDEE",
                                                 "F8E2555BB2D58A76995A6B897CEAFA032CFA6C27"
                                             };

        private delegate void UpdateStatusDelegate(String message, String pass);
        private delegate void updatefailedlabel(string failnum, int countfailed);
        private delegate void updatesend(int countloop);
        private User userr;
        private bool isTyping;

        private WhatsMessageHandler messageHandler;
        private BackgroundWorker bgWorker;
        private volatile bool isRunning;
        private Dictionary<string, User> userList;
        public Checkconta()
        {
            InitializeComponent();
            ServicePointManager.Expect100Continue = false;
            ServicePointManager.ServerCertificateValidationCallback += CustomCertificateValidation;
            this.userList = new Dictionary<string, User>();
            this.isRunning = true;
            this.bgWorker = new BackgroundWorker();
            this.bgWorker.DoWork += ProcessMessages;
            this.bgWorker.ProgressChanged += NewMessageArrived;
            this.bgWorker.WorkerSupportsCancellation = true;
            this.bgWorker.WorkerReportsProgress = true;
            this.messageHandler = new WhatsMessageHandler();
        }
        private bool CustomCertificateValidation(object sender, System.Security.Cryptography.X509Certificates.X509Certificate certificate, System.Security.Cryptography.X509Certificates.X509Chain chain, System.Net.Security.SslPolicyErrors sslPolicyErrors)
        {
            if (sslPolicyErrors != System.Net.Security.SslPolicyErrors.None)
            {
                if (!WaCertThumbprints.Contains(certificate.GetCertHashString()))
                    return this.AskCertificateApproval(sslPolicyErrors, certificate);
            }
            return true;
        }

        private bool AskCertificateApproval(System.Net.Security.SslPolicyErrors sslPolicyErrors, System.Security.Cryptography.X509Certificates.X509Certificate certificate)
        {
            DialogResult res = MessageBox.Show(this,
               String.Format("Warning: server certificate cannot be verified as trusted (Errors: {0}). Continue?\r\n\r\n{1}", sslPolicyErrors.ToString(), certificate.ToString()),
               "Certificate error",
               MessageBoxButtons.YesNo,
               MessageBoxIcon.Exclamation);
            return res == System.Windows.Forms.DialogResult.Yes;
        }
        private void NewMessageArrived(object sender, ProgressChangedEventArgs args)
        {
            if (args.UserState == null || !(args.UserState is ProtocolTreeNode[]))
                return;

            var tmpMessages = args.UserState as ProtocolTreeNode[];
            foreach (var protocolNode in tmpMessages)
            {
                this.PopulateNewMessage(protocolNode);
            }
        }

        private void PopulateNewMessage(ProtocolTreeNode protocolNode)
        {
            this.GetMessageType(protocolNode);
            this.GetMessageBody(protocolNode);
            this.GetMessageSender(protocolNode);
        }

        private void GetMessageSender(ProtocolTreeNode protocolNode)
        {

        }

        private void GetMessageBody(ProtocolTreeNode protocolNode)
        {

        }

        private void GetMessageType(ProtocolTreeNode protocolNode)
        {

        }

        private void ProcessMessages(object sender, DoWorkEventArgs e)
        {
            if (sender == null)
                return;

            while (this.isRunning)
            {
                if (!WhatSocket.Instance.HasMessages())
                {
                    WhatSocket.Instance.PollMessages();
                    Thread.Sleep(100);
                    continue;
                }

                var tmpMessages = WhatSocket.Instance.GetAllMessages();
                (sender as BackgroundWorker).ReportProgress(1, tmpMessages);
            }
        }
        private void timerTyping_Tick(object sender, EventArgs e)
        {
            if (this.isTyping)
            {
                this.isTyping = false;
                return;
            }
            WhatSocket.Instance.SendPaused(this.userr.WhatsUser.GetFullJid());
            //this.timerTyping.Stop();
        }
        private void WhatsEventHandlerOnIsTypingEvent(string from, bool value)
        {
            if (!this.userr.WhatsUser.GetFullJid().Equals(from))
                return;


        }

        private void WhatsEventHandlerOnMessageRecievedEvent(WhatsAppApi.Parser.FMessage mess)
        {
            var tmpMes = mess.data;
            this.AddNewText(this.userr.UserName, tmpMes);
        }

        private void AddNewText(string p, string tmpMes)
        {

        }
        private bool CheckLogin(string user, string pass, string nikenamee)
        {
            try
            {
                if (string.IsNullOrEmpty(user) || string.IsNullOrEmpty(pass))
                    return false;

                WhatSocket.Create(user, pass, nikenamee, true);
                //  MessageBox.Show("creat");
                WhatSocket.Instance.Connect();
                //  MessageBox.Show("connect");
                WhatSocket.Instance.Login();
                //check login status
                if (WhatSocket.Instance.ConnectionStatus == WhatsAppApi.WhatsApp.CONNECTION_STATUS.LOGGEDIN)
                {
                    return true;
                }
            }
            catch (Exception)
            { }
            return false;
        }
        private void button1_Click(object sender, EventArgs e)
        {
            string[] num={"201018106101","201010432512","201281214102","201004412644","201000967204","201002639112"};
            if (!this.CheckLogin("201212414974", "Niy969EGhSijtgrPD4m9Ur4cig0=", "Adv"))
            {


                MessageBox.Show("Failed login");
                return;
              
                
            }
            MessageBox.Show("suc login");
            WhatSocket.Instance.SendSync(num, WhatsAppApi.ApiBase.SyncMode.Full, WhatsAppApi.ApiBase.SyncContext.Background, 0, true);
          WhatSocket.Instance.OnGetSyncResult+=Instance_OnGetSyncResult;
            // WhatSocket.Instance.PollMessages();


        }

        private void Instance_OnGetSyncResult(int index, string sid, Dictionary<string, string> existingUsers, string[] failedNumbers)
        {
            //txt(String.Format("Sync result for {0}:", sid));
            foreach (KeyValuePair<string, string> item in existingUsers)
            {
                if (textBox1.Text.Length == 0)
                {
                    textBox1.Text = item.Key.Substring(1);
                }
                else
                {
                    textBox1.Text += "\r\n" + item.Key.Substring(1);
                }
            }

            foreach (string item in failedNumbers)
            {
                if (textBox2.Text.Length == 0)
                {
                    textBox2.Text = item.Substring(1);
                }
                else
                {
                    textBox2.Text = "\r\n" + item.Substring(1);
                }
            }
        }

        
        private void wa_OnGetSyncResult(int index, string sid, Dictionary<string, string> existingUsers, string[] failedNumbers)
        {
           
        }
    }
}

**Comment by hpatel4u** [comment]
@beljk  check this code once..

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using WhatsAppApi.Account;
using WhatsAppApi.Helper;
using WhatsAppApi.Parser;
using WhatsAppApi.Response;

namespace WhatsAppPort
{
    public partial class frmFilterContacts : Form
    {
        public frmFilterContacts()
        {
            InitializeComponent();
            WhatSocket.Instance.OnGetSyncResult += Instance_OnGetSyncResult;
        }

        private void btnFilterContact_Click(object sender, EventArgs e)
        {
            string[] num = { "201018106101", "201010432512", "201281214102", "201004412644", "201000967204", "201002639112" };

            WhatSocket.Instance.SendSync(num, WhatsAppApi.ApiBase.SyncMode.Full, WhatsAppApi.ApiBase.SyncContext.Background, 0, true);
        }
        private void Instance_OnGetSyncResult(int index, string sid, Dictionary<string, string> existingUsers, string[] failedNumbers)
        {
            string _existsNumbers = string.Empty;
            string _failedNumbers = string.Empty;
            //txt(String.Format("Sync result for {0}:", sid));
            foreach (KeyValuePair<string, string> item in existingUsers)
            {
                if (_existsNumbers.Length == 0)
                {
                    _existsNumbers = item.Key.Substring(1);
                }
                else
                {
                    _existsNumbers+= "\r\n" + item.Key.Substring(1);
                }
            }

            foreach (string item in failedNumbers)
            {
                if (_failedNumbers.Length == 0)
                {
                    _failedNumbers = item.Substring(1);
                }
                else
                {
                    _failedNumbers = "\r\n" + item.Substring(1);
                }
            }
        }
    }
}

**Comment by mgp25** [comment]
@beljk @hpatel4u get used to quote the code

I just try it in my side, and its working perfectly, i synced a few number and got the result in 1 second.

Regards

**Comment by hpatel4u** [comment]
@mgp25 Noted and thank you for your support :+1:

**Comment by beljk** [comment]
@hpatel4u I tested your code but instance is null ... What's wrong ?

**Comment by beljk** [comment]
is must number login when sync or what ??

**Comment by hpatel4u** [comment]
@beljk Yes of course and mgp25 :+1: had done good job on this..

Call frmFilterContacts (code given in my last post) from frmAddUser form. It working :100:%.

**Comment by beljk** [comment]
@hpatel4u  Yea :+1:  this work fine dear .. thanks for your effort man .. and @mgp25  Than you man for your support ,You are the best ;)

**Comment by hpatel4u** [comment]
All credit goes to @mgp25 :+1:

**Comment by mahanamiri** [comment]
@hpatel4u 
My problem is, use the following code in asp.net : 
WhatSocket.Instance.OnGetSyncResult += Instance_OnGetSyncResult;
is null
