### ISSUE TITLE
Image Message not send

### ISSUE THREAD

**Issue by ppiyushjv** [mgp25/Chat-API-NET#63]
Hi

```c#
Audio and Video message send but image message not receipt.
            var mp4 = File.ReadAllBytes("D:\\07042010007.MP4");
            var mp3 = File.ReadAllBytes("D:\\titanic_new_version.mp3");
            var img = File.ReadAllBytes("D:\\test.png");
            WhatSocket.Instance.SendMessageImage(txtMobile.Text, img, WhatsAppApi.ApiBase.ImageType.PNG);
            WhatSocket.Instance.SendMessageAudio(txtMobile.Text, mp3, WhatsAppApi.ApiBase.AudioType.MP3);
            WhatSocket.Instance.SendMessageVideo(txtMobile.Text, mp4, WhatsAppApi.ApiBase.VideoType.MP4);
```
 

Please help me

**Comment by mgp25** [comment]
Post debug log

**Comment by ppiyushjv** [comment]
Please check this

rx <start from="s.whatsapp.net"></start>


rx <stream:features></stream:features>


rx <challenge>s;��m=d������z'</challenge>


rx <success t="1443131390" props="4" kind="free" status="active" creation="1435329569" expiration="1466865569">�_
շ�J�1��B��N</success>


rx <receipt from="919904700322@s.whatsapp.net" id="1443131083-1" offline="1" t="1443131086"></receipt>


rx <receipt from="919904700322@s.whatsapp.net" type="read" id="1443131083-1" offline="1" t="1443131090"></receipt>


rx <ib from="s.whatsapp.net">
rx   <offline count="2"></offline>
rx </ib>


rx <presence from="917097890076@s.whatsapp.net"></presence>


rx <presence from="919904700322@s.whatsapp.net"></presence>


rx <presence from="919904700322@s.whatsapp.net" type="unavailable" last="1443131391"></presence>


rx <iq from="s.whatsapp.net" type="result" id="1443131392-1">
rx   <duplicate url="https://mmi664.whatsapp.net/d/ApS7g_0ig6Wx-sfA72Q_gtbkf6KYuiLAn6YWp7gndDWQ.png" size="228982" mimetype="image/png" filehash="5/Tw8ayi3YRKNN2aG4HFTiXrKD2nVqyNTY8lLwAhdzQ=" type="image" width="517" height="388"></duplicate>
rx </iq>

**Comment by mgp25** [comment]
@ppiyushjv i dont see the actual iq request and remember to pollMessage

**Comment by ppiyushjv** [comment]
Sorry for that mistake now check it

**Comment by mgp25** [comment]
@ppiyushjv i still dont see in the debug log any request iq

**Comment by ppiyushjv** [comment]
sir this is iq from debug log

rx <iq from="s.whatsapp.net" type="result" id="1443131392-1">
rx   <duplicate url="https://mmi664.whatsapp.net/d/ApS7g_0ig6Wx-sfA72Q_gtbkf6KYuiLAn6YWp7gndDWQ.png" size="228982" mimetype="image/png" filehash="5/Tw8ayi3YRKNN2aG4HFTiXrKD2nVqyNTY8lLwAhdzQ=" type="image" width="517" height="388"></duplicate>
rx </iq>

**Comment by mgp25** [comment]
@ppiyushjv first of all quote your code and debug log. Second, thats not the request iq, thats the result

**Comment by ppiyushjv** [comment]
Hello Sir,
First of all sorry but i do not know what you want i have give complete log so please tell me what you you want otherwise i will give my code. When i send image from after text msg also not work.
My project link : https://www.dropbox.com/s/tppvh8pvr9xh9n9/WhatsApp.rar?dl=0
Sir please help me and do not close my issue
