### ISSUE TITLE
Is it possible to decypher messages sent from a single User?

### ISSUE THREAD

**Issue by hannydan** [mgp25/Chat-API-NET#64]
If it's in a group, the message is sent ok - not encrypted,
but when it's  a single User  the message is sent encrypted

Anyone?

**Comment by eduardo-bressan** [comment]
For aught I know, haven't a solution yet, but on te another project in PHP they are writing the algorithm to decrypt.

**Comment by hannydan** [comment]
Hi,
Where can I find the exact PHP code for it?

**Comment by eduardo-bressan** [comment]
I think that only a phyton project has it.

**Comment by mgp25** [comment]
@hannydan wrong. https://github.com/mgp25/libaxolotl-php

**Comment by hannydan** [comment]
10x Eduardo!

Where exactly can I find it in that project?

Regards,
Dan

**Comment by hannydan** [comment]
Hi @mgp25 

Where in the axolotl php  can I find it?
10x!
