### ISSUE TITLE
How to handle onGetGroups event?

### ISSUE THREAD

**Issue by EgyptianM** [mgp25/Chat-API-NET#65]
How to handle onGetGroups event?
how to receive it and get group ID from it?
I need a piece of code as an example
thank you all

**Comment by EgyptianM** [comment]
I got it to work but it doesn't return any groups

how to get group ID from it?

I'm trying to get it from the groups parameter but it doesn't return anything

this is my code
private void OnGetGroups(WhatsAppApi.Response.WaGroupInfo[] groups)
        {
            this.Invoke(new MethodInvoker(delegate()
            {
                this.textBox1.Text += groups.ToString();
            }));
        }
put it just gives me this result in the textbox

WhatsAppApi.Response.WaGroupInfo[]

thank you all

**Comment by JulioImolesi** [comment]
take a look at #39

**Comment by EgyptianM** [comment]
@JulioImolesi  thank you very much
yes it's working now :)
