### ISSUE TITLE
UserAgent Iphone

### ISSUE THREAD

**Issue by eduardo-bressan** [mgp25/Chat-API-NET#66]
I did the reset on the number, but i'm still getting encrypted messages, but when I receive messages from a WhatsApp in a iPhone 4 the messages aren't encrypted. I guess with I use that particularly version on the Api all messages in text/plain even if the the App is updated.

The version is:
WhatsApp = 2.12.2
IOS = 7.1.1

UserAgent = "WhatsApp/2.12.2 iPhone/??? Device/iPhone" ???

**Comment by eduardo-bressan** [comment]
I'm not been able to construct the UserAgent correctly...

**Comment by mgp25** [comment]
Setting iOS User Agent makes no sense, we dont have token generator for iphone
