### ISSUE TITLE
connection not being alive

### ISSUE THREAD

**Issue by yndmai45** [mgp25/Chat-API-NET#69]
everything was working fine, but a few days ago the connection began to steadily fall after a few minutes online in about 1-2 hours online, receiving and answering messages I get the message:
```
<stream: error> <system-shutdown> </ system-shutdown> </ stream: error>
```

**Comment by yndmai45** [comment]
how to best time for delay ?
```
Thread.Sleep(89000);
this.Instance.SendPing();

and

Thread.Sleep(90000);//49000
this.Instance.SendActive();
```

**Comment by mgp25** [comment]
send ping every 1 minute or so
