### ISSUE TITLE
Send Image Message

### ISSUE THREAD

**Issue by alijundi** [mgp25/Chat-API-NET#7]
Hi @mgp25 while I am trying to collect debug information for the invalid token issue I discovered that the function sendimagemessage is not working. I was unable to send a picture message.

Can you please confirm?

**Comment by mmalbergier** [comment]
I got it working by changing the UploadFile method and using a Thread.Sleep instead of the pollMessage:

```c#
int i = 0;
while (this.uploadResponse == null && i <= 10)
{
	i++;
	System.Threading.Thread.Sleep(500);
}
```

**Comment by alijundi** [comment]
Thanks i will try it and get back to you

**Comment by hpatel4u** [comment]
@alijundi and @mmalbergier instead of while loop try with do while.

            do{
                if (!IsUserPolling)
                {
                    this.pollMessage();
                }
                lock (this.uploadResponses)
                {
                    if (uploadResponses.TryGetValue(id, out uploadResponse))
                    {
                        uploadResponses.Remove(id);
                        break;
                    }
                }
                Thread.Sleep(200);
                ++i;
            }while(i <= 10);

**Comment by alijundi** [comment]
sorry @hpatel4u and @mmalbergier the above solutions did not work with me. it seems that I receive the response but after breaking the while look. Like if the system thread is simply waiting until the while loop is finished

**Comment by alijundi** [comment]
I run the sendimage function in a separate thread and add getJID(to) to the send algorithm. Everything is fine now.

**Comment by mgp25** [comment]
There are few things i neeed to update yet (compare it with Chat API), if anyone wants, send a pull request, if not when i have some free time ill do it

**Comment by sebas0066** [comment]
Hi, i have a question, how i run it on separate thread?, some can put an example please. Thanks
