### ISSUE TITLE
How to set group admins

### ISSUE THREAD

**Issue by inornos** [mgp25/Chat-API-NET#70]
How to set group admins? There are no other method mentioned in wiki

**Comment by mgp25** [comment]
There are no coded functions for promoting an user in Chat API NET yet, you can port the function from Chat API php and send a pull request.

Regards

**Comment by divieirasilva** [comment]
Hello, if anyone still need it, i've ported the functions...

    public void SendGroupsChangeParticipants(string gjid, IEnumerable<string> participants, string tag, string id)
        {
            IEnumerable<ProtocolTreeNode> source = from jid in participants
                                                   select new ProtocolTreeNode("participant", new[] { new KeyValue("jid", GetJID(jid)) });

            var child = new ProtocolTreeNode(tag, null, source);
            var node = new ProtocolTreeNode(
                "iq", 
                new[] {
                    new KeyValue("id", id),
                    new KeyValue("type", "set"),
                    new KeyValue("xmlns", "w:g2"),
                    new KeyValue("to", GetJID(gjid))
                }, 
                child
            );

            this.SendNode(node);
        }


    public void SendPromoteParticipants(string gjid, IEnumerable<string> participants)
        {
            string id = TicketCounter.MakeId();
            this.SendGroupsChangeParticipants(gjid, participants, "promote", id);
        }

**Comment by mgp25** [comment]
@divieirasilva send a pull request
