### ISSUE TITLE
how to decrypt incoming message in this event wa_OnGetMessage

### ISSUE THREAD

**Issue by MAK11** [mgp25/Chat-API-NET#72]
wa_OnGetMessage fires when there is an incoming message, but the messages are encrypted how do i decrypt it to plain text ?

**Comment by mgp25** [comment]
https://github.com/mgp25/Chat-API-NET/issues/64#issuecomment-146289451

**Comment by hannydan** [comment]
Hi @MAK11 
If you find a solution,
please share :)
10x
