### ISSUE TITLE
"Login failed. Reason: Non - authorized". How to check blocked my numer or not ?

### ISSUE THREAD

**Issue by bgani** [mgp25/Chat-API-NET#75]
Hello, I got "Login failed. Reason: Non - authorized"  yesterday. I tried to use new password from WART, but it returned me same issue. After 5 hours i tried again and login success. 
1. How can i check my numer blocked or not ?  

If my number blocked, I didn't not use Chat-API-NET as should. And i want to know how use it right way. I send messages only two contacts, and they have my number in their contact list. But..
2. Should I Sync contacts in each login session ?
3. Should I Send Typing and Send Paused even i don't need it ? (I never send typing)

**Comment by mgp25** [comment]
http://www.watools.es/bloqueado.html
