### ISSUE TITLE
SendSync issue

### ISSUE THREAD

**Issue by sebas0066** [mgp25/Chat-API-NET#79]
Hi, i try to do a webservice using VB.NET and when i call the Sendsync and next pollmessages() it takes like 1 o 2 minutes on respond with the answer. i have here mi code:

    Public Function CheckWP(ByVal contact As String, Fromnum As String, passwp As String) As String

        WANum = Fromnum
        WAPass = passwp

        Dim contacto() As String
        cont = "+" & contact

        InitWA("NickName")

        ReDim contacto(0)
        contacto(0) = contact
        wa.SendSync(contacto, WhatsAppApi.ApiBase.SyncMode.Full, WhatsAppApi.ApiBase.SyncContext.Interactive, 0, True)
        wa.PollMessages()

        Return resultSync

    End Function

**Comment by mgp25** [comment]
bad function used, see examples
