### ISSUE TITLE
Ping response error

### ISSUE THREAD

**Issue by alijundi** [mgp25/Chat-API-NET#8]
It seems and after a while of being online I receive a ping request from WA server and the API responds with a ping accordingly. After that, a stream error occurs marked system-shutdown.

I believe there is something wrong in the formation of the iq result node. If any body can help I would appreciate it, I really need to stay online and not get disconnected.

```xml
rx <iq from="s.whatsapp.net" id="1431627842-ping" type="get" xmlns="urn:xmpp:ping"></iq>
DEBUG: 
tx <iq type="result" to="s.whatsapp.net" id="1431627842-ping"></iq>
DEBUG: 
rx <stream:error>
rx   <system-shutdown></system-shutdown>
rx </stream:error>
Connection LOST
```

**Comment by mgp25** [comment]
@alijundi can you try again? its working to me

**Comment by alijundi** [comment]
@mgp25 I modified the order of the key values in the response to be 

```xml
tx <iq to="s.whatsapp.net" id="1431627842-ping" type="result"></iq>
```
and I put to test. After a ping is received pong is sent without stream error. I, However, need to test it for a long period which I will do this night. I will keep you posted on the update by tomorrow.

**Comment by mgp25** [comment]
@alijundi sure, send a Pull request when confirmed.

Regards

**Comment by manolomad** [comment]
Hi, @MGP25: I have similar problem. System-shutdown each two hours. Ping doesn't make any effect to the server.
