### ISSUE TITLE
Encrypted messages

### ISSUE THREAD

**Issue by kuleshows** [mgp25/Chat-API-NET#81]
I have a problem with enctypted messages. I started using new phone number, and started getting encrypted messages. Could you please help me with that issue?

**Comment by guilhermecruz87** [comment]
Me too!!
Help?

**Comment by mgp25** [comment]
I dont have enought time to implement axolotl in .NET API, axolotl is required in order to support end to end encryption.

Chat API (php) has this already implemented: https://github.com/WHAnonymous/Chat-API

Regards
