### ISSUE TITLE
sync contact only when number unauthorized

### ISSUE THREAD

**Issue by beljk** [mgp25/Chat-API-NET#9]
my number sync when only unauthorized  ... before send the first message I sync contact and found my number unauthorized and send message after sync but when send message again I found my number login and don't sync contact
@mgp25

**Comment by mgp25** [comment]
@beljk post debug log and code

**Comment by beljk** [comment]
{"BinTreeNodeReader->readListSize: Invalid token 246"} ... I found this error when send some messge

**Comment by beljk** [comment]
private void ProcessMessages(object sender, DoWorkEventArgs e)
        {
            if (sender == null)
                return;

            while (this.isRunning)
            {
                if (!WhatSocket.Instance.HasMessages())
                {
                    WhatSocket.Instance.PollMessages(); >>>>>>>>>>>>>>>>>> Error here
                    Thread.Sleep(100);
                    continue;
                }

                var tmpMessages = WhatSocket.Instance.GetAllMessages();
                (sender as BackgroundWorker).ReportProgress(1, tmpMessages);
            }
        }

**Comment by mgp25** [comment]
Not the API code, i mean your code and the debug log. If you dont post that i cant help you

**Comment by beljk** [comment]
I will get it to you but what about the number unauthorized ? and if I register numbers with the same salt and IP ,it's get block ??

**Comment by mgp25** [comment]
I will wait for code and debug lo

Regards
