### ISSUE TITLE
Imageboradcast problem

### ISSUE THREAD

**Issue by Mahmoud85** [mgp25/Chat-API-NET#90]
hello mgp25
I have a problem in image broadcasting , I was unable to send images at all weather in chat or broadcast , so I got your solution and modified the code to run it as below,no I'm able to send image using the imagebroadcast method but only to one user if added another user to send to , no thing being sent though I got no errors , please help.

```c#
while (this.uploadResponse == null && i <= 500)
            {
                var newthread = new Thread(t =>
                {
                    try
                    {
                        i++;
                        //this.pollMessage();
                        Thread.Sleep(100);

                    }
                    catch (ThreadAbortException)
                    {
                    }
                })
                { IsBackground = true };
                newthread.Start();
```

**Comment by mgp25** [comment]
@Mahmoud85 post debug log

**Comment by Mahmoud85** [comment]
mgp25 I'm afraid it exit without having the log
I think the problem is with the line this.pollMessage(); because when I use it nothing being sent at all but when I remove it I can only send a broadcastimage to one contact if I added another nothing being sent without getting any error.

**Comment by mgp25** [comment]
@Mahmoud85 retry again and post debug log

**Comment by Mahmoud85** [comment]
mgp25 please advise if there is a way to get the debug log

**Comment by Mahmoud85** [comment]
'WhatsAppPort.vshost.exe' (CLR v4.0.30319: WhatsAppPort.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WhatsAppPort.vshost.exe' (CLR v4.0.30319: WhatsAppPort.vshost.exe): Loaded 'C:\Windows\assembly\GAC_MSIL\Microsoft.VisualStudio.HostingProcess.Utilities\14.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.HostingProcess.Utilities.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WhatsAppPort.vshost.exe' (CLR v4.0.30319: WhatsAppPort.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WhatsAppPort.vshost.exe' (CLR v4.0.30319: WhatsAppPort.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WhatsAppPort.vshost.exe' (CLR v4.0.30319: WhatsAppPort.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Drawing\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Drawing.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WhatsAppPort.vshost.exe' (CLR v4.0.30319: WhatsAppPort.vshost.exe): Loaded 'C:\Windows\assembly\GAC_MSIL\Microsoft.VisualStudio.HostingProcess.Utilities.Sync\14.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.HostingProcess.Utilities.Sync.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WhatsAppPort.vshost.exe' (CLR v4.0.30319: WhatsAppPort.vshost.exe): Loaded 'C:\Windows\assembly\GAC_MSIL\Microsoft.VisualStudio.Debugger.Runtime\14.0.0.0__b03f5f7f11d50a3a\Microsoft.VisualStudio.Debugger.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WhatsAppPort.vshost.exe' (CLR v4.0.30319: WhatsAppPort.vshost.exe): Loaded 'E:\Whats app sender\Chat-API-NET-master\WhatsAppPort\bin\Debug\WhatsAppPort.vshost.exe'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WhatsAppPort.vshost.exe' (CLR v4.0.30319: WhatsAppPort.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WhatsAppPort.vshost.exe' (CLR v4.0.30319: WhatsAppPort.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml.Linq\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.Linq.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WhatsAppPort.vshost.exe' (CLR v4.0.30319: WhatsAppPort.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Data.DataSetExtensions\v4.0_4.0.0.0__b77a5c561934e089\System.Data.DataSetExtensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WhatsAppPort.vshost.exe' (CLR v4.0.30319: WhatsAppPort.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WhatsAppPort.vshost.exe' (CLR v4.0.30319: WhatsAppPort.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Deployment\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Deployment.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WhatsAppPort.vshost.exe' (CLR v4.0.30319: WhatsAppPort.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
The thread 0x351c has exited with code 0 (0x0).
The thread 0x3f68 has exited with code 0 (0x0).
The thread 0x2154 has exited with code 0 (0x0).
'WhatsAppPort.vshost.exe' (CLR v4.0.30319: WhatsAppPort.vshost.exe): Loaded 'E:\Whats app sender\Chat-API-NET-master\WhatsAppPort\bin\Debug\WhatsAppPort.exe'. Symbols loaded.
'WhatsAppPort.vshost.exe' (CLR v4.0.30319: WhatsAppPort.vshost.exe): Loaded 'E:\Whats app sender\Chat-API-NET-master\WhatsAppPort\bin\Debug\WhatsAppApi.dll'. Symbols loaded.
'WhatsAppPort.vshost.exe' (CLR v4.0.30319: WhatsAppPort.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'WhatsAppPort.vshost.exe' (CLR v4.0.30319: WhatsAppPort.vshost.exe): Loaded 'C:\Windows\assembly\GAC_MSIL\Microsoft.Office.Interop.Excel\15.0.0.0__71e9bce111e9429c\Microsoft.Office.Interop.Excel.dll'. Module was built without symbols.
'WhatsAppPort.vshost.exe' (CLR v4.0.30319: WhatsAppPort.vshost.exe): Loaded 'C:\Windows\assembly\GAC_MSIL\office\15.0.0.0__71e9bce111e9429c\office.dll'. Module was built without symbols.
'WhatsAppPort.vshost.exe' (CLR v4.0.30319: WhatsAppPort.vshost.exe): Loaded 'C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Web.Extensions\v4.0_4.0.0.0__31bf3856ad364e35\System.Web.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Exception thrown: 'System.NullReferenceException' in WhatsAppApi.dll
The thread 0x1bd0 has exited with code 0 (0x0).

**Comment by mgp25** [comment]
@Mahmoud85 thats not debug log

**Comment by Mahmoud85** [comment]
ok , I think , I should make a new thread for the pollmessage() method , so could you give me an example of how to do that
