### ISSUE TITLE
Error in SIM activation

### ISSUE THREAD

**Issue by alex696** [mgp25/Chat-API-NET#92]
Dear mgp25,

when I try to activate a new phone number with WART I receive the activation message, but when I type the welcome message and I confirm that I receive the message

{"status":"fail","reason":"temporarily_unavailable","retry_after":3600}

If i try to activate a number after 1 hour the response is 

{"status":"fail","reason":"blocked"}

Could you get me any suggest?

Best regards

**Comment by mgp25** [comment]
Blocked network / Bad behaviour / Spamming / Massive requests

You have done one of the above. I recommend you to use `registerTool.php`to check if it works okay

Regards
